### ISSUE TITLE
Bug in CCOpt.filter?

### ISSUE THREAD

**Issue by reubenrowe** [c-cube/ocaml-containers#100]
CCOpt.filter currently has the following implementation:

``` 
let filter p = function
    | Some x as o when p x -> o
    | o -> o
```

So, behaves as the identity function on the option value - I guess this is a bug, and the intended behaviour is:

``` 
let filter p = function
    | Some x as o when p x -> o
    | _ -> None
```

**Comment by c-cube** [comment]
Thanks for the report. The simpler the function, the more stupid errors are -_-

**Comment by c-cube** [comment]
I'm making a new release with the bugfix in it!

**Comment by reubenrowe** [comment]
Thanks :-)
