### ISSUE TITLE
list of fold results?

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#101]
i was wondering if a function that lists successive fold results would be a good addition? i think in haskell this is scanl/scanr and in Mathematica FoldList? i think it should give something like this:
```
fun f init l -> List.fold_left (fun acc item -> f item (List.hd acc) :: acc) [init] l
```
so that `List.hd` of the result equals `List.fold_left f init l`. there already is `fold_map` but i found that more complicated. using `fold_map`, i did not see how to get exactly what the function above gives, i.e. all fold results including the last.

---

edit from @c-cube for tracking:
- [x] `List.scan` (with first accumulator and last)
- [x] `Array.fold_map`
- [x] `Array.scan`

**Comment by nilsbecker** [comment]
and potentially something similar for array?

**Comment by c-cube** [comment]
I thought I had this, but no, it's in `gen` and `sequence`. I will write it.
It's also useful to use `Sequence.scan : ('b -> 'a -> 'b) -> 'b -> 'a t -> 'b t` in general, for other containers!

**Comment by c-cube** [comment]
Note that indeed, `fold_map` should already work in some cases?

```ocaml
# CCList.fold_map (fun acc x -> acc+x,acc) 0 CCList.(0 -- 10);;
- : int * int list = (55, [0; 0; 1; 3; 6; 10; 15; 21; 28; 36; 45])
# CCList.fold_map (fun acc x -> acc+x,acc+x) 0 CCList.(0 -- 10);;
- : int * int list = (55, [0; 1; 3; 6; 10; 15; 21; 28; 36; 45; 55])
```

**Comment by nilsbecker** [comment]
i guess that's a general question: should one always try to transform to a `Sequence.t` and do everything there? that could save duplication of effort, but is a little less convenient.

**Comment by nilsbecker** [comment]
ah, i had not found the second line. it requires a little thinking i guess.

**Comment by c-cube** [comment]
always going to `Sequence` isn't necessarily good, but it's really useful for containers that are opaque and lack useful functions (e.g. Hashtbl, Queue) or if you are going to chain a lot of transformations including things like map, filter and `flat_map`.

In this particular case, I think `fold_map` works fine in the end? You can prepend the initial accumulator to get `n+1` elements. I can write a shortcut function but I'd like a better name than `scan`…

**Comment by nilsbecker** [comment]
well it's up to you: is the shortcut useful or clutter of the interface? personally i think, probably still useful... for a name: `fold_list`?

**Comment by nilsbecker** [comment]
so then, what is the best way to write a cumulative sum of an array? 
```
Array.(1--5)
|> Sequence.of_array
|> Sequence.scan (+) 0
|> Sequence.drop 1
|> Sequence.to_array;;
- : int array = [|1; 3; 6; 10; 15|]
```
?
or would you also consider a "fold_list" function for arrays?

**Comment by c-cube** [comment]
Ah indeed, for arrays there is not even a `fold_map`. I will write it.
