### ISSUE TITLE
CCFormat color handling has stateful bug

### ISSUE THREAD

**Issue by Gbury** [c-cube/ocaml-containers#103]
It seems `CCFormat.with_colorf` has a bug triggered by the code in https://gist.github.com/Gbury/b3394a359d08be9d47eb084ebbbb492b

**Comment by c-cube** [comment]
I think that's becaues of "@.".

**Comment by c-cube** [comment]
I'm not sure if it's valid to close a tag *after* a "@." (since this assumes everything is flushed, including perhaps tags?). Would @gasche know, by any chance?

**Comment by c-cube** [comment]
https://caml.inria.fr/mantis/view.php?id=6769

**Comment by Gbury** [comment]
The Mantis PR seems to suggest that a flush should close all currently open tags (in which case the style should be returned to normal after a flush, which would suit me), so why is it not the case ?

Putting that aside, what would then be the correct way to have code similar to what is in the gist ? Is it possible to have a parametric tag for styles ? (much like what is done for the width and precision of floats and integers ?) Or maybe the `with_colorf` function could work without using tags ?

**Comment by c-cube** [comment]
I think the tags are closed but their callback is not called. And no, the whole color system is based on tags (0-width). I don't think parametric tags exist (except maybe with `pp_open_tag`)
