### ISSUE TITLE
A fork of ocaml-containers for Bucklescript

### ISSUE THREAD

**Issue by dorafmon** [c-cube/ocaml-containers#104]
Hi, I forked this repo [here](https://github.com/dorafmon/bs-containers) and made it compile with the [Bucklescript compiler](https://github.com/bloomberg/bucklescrip) which compiles OCaml to Javascript. Please let me know if you have any concerns. Thanks a lot!

Best,
Bob

**Comment by c-cube** [comment]
No problem at all. I'd appreciate if you forward bug reports/bug fixes upstream, but otherwise it's a BSD-licensed project! :-)

**Comment by dorafmon** [comment]
Sure! Thanks a lot!
