### ISSUE TITLE
Bresult.fold is incorrect

### ISSUE THREAD

**Issue by glennsl** [c-cube/ocaml-containers#107]
The signature of `Bresult.fold` is
```ml
val fold : ok:('a -> 'b) -> error:('err -> 'b) -> ('a, 'err) t -> 'b
```

Compare this to `Bopt.fold`, which I think is correct (although with confusing ordering of type vars)
```ml
val fold : ('a -> 'b -> 'a) -> 'a -> 'b t -> 'a
```

Instead it is pretty much equivalent to `Bresult.catch` (even the different order of arguments isn't really significant)
```ml
val catch : ('a, 'err) t -> ok:('a -> 'b) -> err:('err -> 'b) -> 'b
```

The correct signature I think is this:
```ml
val fold : ('b -> 'a -> 'b) -> 'b -> ('a, 'err) t -> ('b, 'err) t
```

**Comment by c-cube** [comment]
I would not call it "incorrect", as it is a form of catamorphism; I reckon that a more `List.fold_left`-like signature would be useful. It would be:

```ocaml
val fold_ok : ('a -> 'b -> 'a) -> 'a -> ('b, _) t -> 'a`
```

**Comment by glennsl** [comment]
Ah, yes I see I screwed up the "correct" signature too.

But then what about `CCOpt.fold`? That's still not consistent with `CCResult.fold`. And should `catch` perhaps be an alias for `fold`?
