### ISSUE TITLE
include `List` in `CCList`, etc.

### ISSUE THREAD

**Issue by c-cube** [c-cube/ocaml-containers#109]
would concern:

- `CCList`, `CCListLabels`
- `CCArray`, `CCArrayLabels`
- `CCString`
- `CCMap`, `CCSet`, `CCHashtbl? not sure it's easy to do
- `CCRandom`

perhaps `CCUnix`?

**Comment by orbitz** [comment]
I am of two different minds on this:

1. It's quite nice to keep containers lean and only those things where it adds value.  In that sense, I'm for not including the stdlib module in the container module.
1. It's annoying to have to know which module to look into for a function.

I think that it might be useful to consider how containers might look in a few years to see if this is a good idea or not.

**Comment by nilsbecker** [comment]
i never had this issue? i guess this is because i always `open Containers` and the namespaces merge? basically, is the idea that one should not have to pull in all of containers to get this convenience?

**Comment by c-cube** [comment]
It's not too costly with module aliases, I think? As long as you don't use `Array`, you won't link against the extended `CCArray`.

**Comment by c-cube** [comment]
@nilsbecker indeed, the idea is  that you could `module List = CCList` without inconvenience, and without pulling all of containers. Anyway, `open Containers` should more or less do the same since it (mostly) relies on module aliases…

**Comment by c-cube** [comment]
So I'm wondering whether to only do that for "big" modules (list, array) or for all modules which extend the stdlib ones…

**Comment by orbitz** [comment]
FWIW, I'm more interested in not having to search multiple places to find a common `List` function than if `CCList` is backwards compatible with `List`.

Also, are you considering the `*Label`'s modules as well?  How expensive is this whole thing going to become with all these modules?

Another related point is I was surprised that `CCMap.Make(CCString)` did not work because `CCString` does not match the expected type of `CCMap`.

**Comment by c-cube** [comment]
I'd consider String too, and labels, yes (`{List, Array, String}`, perhaps `Int64`). It's more difficult for `{Set,Map,Hashtbl}` because of functor collisions…

**Comment by c-cube** [comment]
This might actually become 2.0, if I rename the functors and signatures in `Hashtbl,Map,Set` so that inclusion does not collide.
