### ISSUE TITLE
Document the behaviour of lossy conversion functions

### ISSUE THREAD

**Issue by copy** [c-cube/ocaml-containers#118]
"lossy" conversion functions, such as `CCFloat.to_int`, `CCFloat.of_int`, `CCInt64.to_*` should be documented to have such behaviour, since it's not obvious from the name or type signature whether they raise or are lossy.

By the way, `CCFloat.of_string` seems to be an outlier, as it raises but doesn't have `_exn` in its name.

**Comment by c-cube** [comment]
you have an eye for the corner cases.

**Comment by c-cube** [comment]
That would break compatibility, though :/
I need to add documentation, but since it's just aliases to pervasives functions…

**Comment by copy** [comment]
> That would break compatibility, though :/

Yeah, you could put it on the todo list for Containers 2.0 or deprecate it so users at least get a warning.
