### ISSUE TITLE
CCFun.on

### ISSUE THREAD

**Issue by copy** [c-cube/ocaml-containers#119]
A more general version of `CCEqual.map` that also works with `compare` would be useful, akin to Haskell's `on`: https://hackage.haskell.org/package/base-4.9.1.0/docs/Data-Function.html#v:on

**Comment by c-cube** [comment]
Isn't it the same as `CCFun.compose_binop`? I picked a longer name because I find it more readable :-)

**Comment by copy** [comment]
Indeed, somehow I missed that.
