### ISSUE TITLE
List.filter_some

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#124]
i have sometimes found i need `List.filter_map (fun x -> x)` on lists that are already of type `'a option list` from upstream. would it make sense to have an extra function `List.filter_some` for that? (same question for other collections and sequences)

**Comment by c-cube** [comment]
It makes sense. Should it be called `remove_nones` instead?

Also: `'a option list -> 'a list option` is missing…

**Comment by nilsbecker** [comment]
yes, `filter_some` may be bad as it suggests to filter away the `Some _` instances. `remove_nones` is also a bit unlucky, since the `Some` constructor is also removed. `List.filter_option`? `get_option`?

**Comment by hcarty** [comment]
Could be nice to have similar function for `Ok _`/`Error _`.  Would it make sense to provide functions for each of those types which fit nicely into `List.filter_map` or a new but still relatively generic function?

**Comment by c-cube** [comment]
good remark, @hcarty . I'll decide on the names when I solve this :-)

**Comment by hcarty** [comment]
Maybe something along the lines of:
```ocaml
(* Arguably already there for 'a option? *)
CCList.filter_map CCFun.id list_of_options

(* If we have [CCResult.get_ok : ('ok, _) result -> 'ok option] *)
CCList.filter_map CCResult.get_ok list_of_results
```
and then `Gen` and everything else with a similar `filter_map` function can benefit too.

**Comment by c-cube** [comment]
There is `CCResult.to_opt`.

**Comment by hcarty** [comment]
Thanks @c-cube - updated my comment to match.
