### ISSUE TITLE
CCRingBuffer extensions

### ISSUE THREAD

**Issue by copy** [c-cube/ocaml-containers#127]
The following would be useful:

- `is_full`
- option-returning variants of `peek_front`, `peek_back` (preferably backwards-incompatible)

**Comment by c-cube** [comment]
Compatibility shall be maintained, sorry. But option-returning variants are totally possible.

**Comment by c-cube** [comment]
Change of mind: breaking compatibility a bit, with `_exn` variants, is totally possible and should be part of the effort in #134. `is_full` is quite easy to add, too.
