### ISSUE TITLE
compilation warnings about missing cmx (58)

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#128]
hi, i get these warnings:
```
Warning 58: no cmx file was found in path for module CCFun, and its interface was not compiled with -opaque
File "_none_", line 1:
Warning 58: no cmx file was found in path for module CCString, and its interface was not compiled with -opaque
```
is this expected? am i doing something wrong? the reported command line is 
```
+ ocamlfind ocamlopt -c -g -bin-annot -principal -O3 -w A-48-42 -package 'csv, gsl, containers, sequence, lacaml, bigarray, gen, parmap' -package 'ctypes, ctypes.foreign' -o hmtree.cmx hmtree.ml
```

**Comment by c-cube** [comment]
Yes, this is "normal", it's due to oasis not installing the .cmx files for modules preprocessed by cppo. I don't really have the time to fix this kind of "small" issues (which don't matter much as far as I know?)

**Comment by c-cube** [comment]
I'm going to close this unless you can convince me that this is critical ;-)

**Comment by nilsbecker** [comment]
no problem. just thought i'd mention it in case it is an oversight.
