### ISSUE TITLE
Getting warning while using CCFun

### ISSUE THREAD

**Issue by bikalgurung** [c-cube/ocaml-containers#137]
I am getting the following error while using (>>) from CCFun module.
```Warning 58: no cmx file was found in path for module CCFun, and its interface was not compiled with -opaque```

I am using jbuilder to build the project. Is there some setting that I need to use? perhaps an ocamlopt flag?

**Comment by c-cube** [comment]
Hello! It's not an error, simply a warning, caused by a limitation of oasis (which is used to build containers). On the other hand, `>>` is not a value in `CCFun`…

**Comment by bikalgurung** [comment]
Hi, thanks for the response. 

> On the other hand, >> is not a value in CCFun…

Yep, you are right. I have aliased ```>>``` to ```CCFun.(%>)```. 

Indeed it is a warning. I kinda treat warnings as errors hence the terminology. From your description, I gather it is okay to silence the error then?

**Comment by c-cube** [comment]
It is ok, yes. I hope this will eventually get fixed, but in the meantime don't worry about it :-)
