### ISSUE TITLE
Hash function for sets

### ISSUE THREAD

**Issue by grayswandyr** [c-cube/ocaml-containers#139]
It would be nice to have a hash function for sets (I don't think there is any).

**Comment by c-cube** [comment]
It's possible to hash a set indirectly, using:

```ocaml
module S = CCSet.Make(String)

let hash_set s = S.to_seq s |> CCHash.(seq string)
```

**Comment by grayswandyr** [comment]
This is what I'm doing at the moment but it doesn't seem optimal.

**Comment by c-cube** [comment]
Why wouldn't it be optimal? :-)
Hashing should care about elements, not about the inner structure of the tree.

**Comment by grayswandyr** [comment]
Well you're right, the problem is rather that I should keep this hash in a record field to avoid recomputing it all the time ;-)

**Comment by c-cube** [comment]
Ah, this is a different issue. You'll need to use a custom structure :-)
