### ISSUE TITLE
CCCache tracing facility

### ISSUE THREAD

**Issue by grayswandyr** [c-cube/ocaml-containers#140]
It would be nice to be able to trace what happens when using a CCCache, for debugging purposes. One possibility would be to add an optional parameter to `with_cache[_rec]` that is passed the function argument (used as a key by the cache) and returns unit.

**Comment by c-cube** [comment]
Would this function be called only on cache miss?

**Comment by grayswandyr** [comment]
Actually, the way I had thought about it would rather to allow printing 
even in case of success. To check whether the cache behaves as expected 
from a user point of view. But your suggestion makes sense also, as it 
may help fine-tuning a good size for the cache.

**Comment by c-cube** [comment]
So why not something like:

```
val with_cache : ?callback:(hit:bool -> 'a -> 'b -> unit) -> ('a,'b) t -> 'a -> 'b
```

**Comment by grayswandyr** [comment]
Seems good to me :+1:
