### ISSUE TITLE
Consider adding a small Prelude 

### ISSUE THREAD

**Issue by grayswandyr** [c-cube/ocaml-containers#142]
I think it would be cool to add small prelude to Containers. This way, opening Containers would not clutter the namespace but could still be followed by an `open Prelude` directive. The said module would contain a short list of useful functions or operators not available in Pervasive, e.g. . To say the truth, most of the functions I can think already exist in Fun but:

1. `Fun` contains more functions than needed (IMO)
2. I guess some other people could think of other functions. E.g. curried constructor functions for base types (`some`, `none`, `cons`...).
3. Operator(s) for one ubiquitous sequential container (`list` or `seq`), most notably `>|=`.

**Comment by c-cube** [comment]
Ok, this is an interesting proposal. It's not clear to me what would become of `CCFun` afterward (except for compat), but a well-designed prelude is indeed a good idea. It should be in its own module, I think (`CCPrelude`, aliased as usual, or `CCStd` to imitate `Core.Std` and the likes).

**Comment by grayswandyr** [comment]
Perhaps a poll on the containers mailing-list would bring some community feedback. Or a post on Discuss/Reddit? Of course,this should be done after a first tentative set is proposed. So I can think of:
```
(%)
(%>)
tap
(>|=) (from List?)
flip
curry
uncurry
identity (= Fun.id but id is too short and too common a name so clashes may happen)
```

**Comment by grayswandyr** [comment]
`Bool.negate` is extremely useful too as it's often needed with `(%)`.

**Comment by bluddy** [comment]
Really doesn't seem like Fun has too many functions too me. Can't we just keep Fun and enhance it?

**Comment by grayswandyr** [comment]
Why not? The main point, to me, is about adding a *small* prelude taking most (or all, as you suggest) of its functions from Fun but also a few functions from other modules (`>|=`, `Bool.negate`, perhaps some functions from `CCPair` like `swap`). So writing only `open Fun` at the beginning of every file is not really enough as of now, and you don't want to add functions to `Fun` that are not related to... well... functions. Hence my proposal for an extra module.

**Comment by bluddy** [comment]
OK I see -- I didn't get the fact that you wanted to include a sample of useful functions from many modules. Then I suggest that CCFun is just wrongly named, and it should be that, expanded to alias some of these other functions.

**Comment by grayswandyr** [comment]
It's a possibility indeed. But I'd rather leave the existing modules as they are, to give more freedom to users, and create a sensible prelude that they could decide to open or not (one could even go as far as adding, say, a `Containers_std` module including `Containers` *and* declaring the said prelude functions: so one `open Containers_std` everywhere would be enough for users agreeing to see the global namespace being enrigh).

**Comment by c-cube** [comment]
I'm not sure there is anything outside of `CCFun` that should live in the prelude, but perhaps it's because `CCFun` should indeed *be* the prelude (renaming + deprecation?). I'm not fond of having a `>|=` at toplevel, it's really ambiguous.

**Comment by grayswandyr** [comment]
Even `negate`? It's very useful as you often stumble upon a predicate written "the other way round". E.g. `Sequence.drop_while` but no  `Sequence.drop_until`.

**Comment by c-cube** [comment]
I should deprecate `negate` since `not` is actually a normal function…

**Comment by grayswandyr** [comment]
Wow I hadn't even realized. Feeling stupid.

**Comment by c-cube** [comment]
Well me too, as I wrote this function :-)

**Comment by c-cube** [comment]
I think `Pervasives` is already full enough. Re-open if you don't feel  the same.
