### ISSUE TITLE
Gradually import parts of Containers into stdlib

### ISSUE THREAD

**Issue by bluddy** [c-cube/ocaml-containers#144]
This doesn't entirely belong here, but since there's no issues on the OCaml repo, I'll put it here anyway.

Containers is a logical and light extension of the stdlib. Therefore, it makes sense to me to gradually import more and more of it into the stdlib. Rather than developing small inconsistent patches on the OCaml repo adding various functions, it makes more sense to view Containers as a possible Boost (from C++) for the standard library -- a sandbox where new ideas can be worked out before they're imported to the stdlib.

The more exotic data structures can probably stay in Containers.

Some of this work may require the [PR that prefixes the stdlib](https://github.com/ocaml/ocaml/pull/1010) for changes to be accepted.

**Comment by c-cube** [comment]
Indeed, I would like to merge/adapt some of containers' code and idioms into the stdlib. See https://gist.github.com/c-cube/7e58ac8d0a1a2797994b0b74fe357628 for some more details. But there is no timeline so far, and it will probably be difficult.

**Comment by UnixJunkie** [comment]
Trying to move the stdlib is a waste of time (and most importantly, of some hacker's energy).
Hacker's energy is best spent at moving forward things that are movable.
Hacker's energy is rare and precious.

**Comment by bluddy** [comment]
The stdlib is what's available in many circumstances. Moving it forward advances the whole ecosystem, because it becomes the new baseline.

**Comment by UnixJunkie** [comment]
people should not use the stdlib, because it is not an extended library, plus it is full of non tail rec code.

**Comment by c-cube** [comment]
This is a bit of a circular reasoning. If we could extend the stdlib, it would becom extended! 😄 
I'm still trying to move things to the stdlib but everything significant is blocked by https://github.com/ocaml/ocaml/pull/1010.

**Comment by c-cube** [comment]
This is now unblocked, but I have 0 motivation for the process for now. @bluddy still interested?

**Comment by kwshi** [comment]
What does the process entail?

**Comment by c-cube** [comment]
A lot of patience. At this point I should just close this issue :sweat_smile:
