### ISSUE TITLE
Switch CC*.pp functions to the CCFormat.list convention

### ISSUE THREAD

**Issue by Gbury** [c-cube/ocaml-containers#148]
The `CCFormat.list` function now takes unit printers for separators, which is quite useful once you get used to it.

However, specific printing functions (such as `CCSet.pp`, `CCArray.pp`, etc...) still uses strings for the separators, so I think it would be nice to switch them to use the same signature as the `CCFormat.list` function.

**Comment by c-cube** [comment]
This would break compatibility. I get the sentiment, but it's not high in my priority list for now… Sorry.
