### ISSUE TITLE
Mismatch between ArrayLabels .ml and .mli

### ISSUE THREAD

**Issue by lostman** [c-cube/ocaml-containers#163]
I've been using `containers` with Reason and it works great but the compiler complained about a mismatch between `CCArrayLabels.ml` and `CCArrayLabels.mli` (and also `CCListLabels.ml` and `CCListLabels.mli`)

For example:

```
(* CCArrayLabels.ml *)
let map2 f a b = ...
```
```
(* CCArrayLabels.mli *)
val map2 : f:('a -> 'b -> 'c) -> 'a t -> 'b t -> 'c t
```

Also, is there a reason that `CCArrayLabels.ml` contains duplicates of functions already implemented in `CCArray.ml`?

For instance, wouldn't this be sufficient:
```
(* CCArrayLabels.ml *)
let map2 ~f xs ys = CCArray.map2 f xs ys
```
?

**Comment by bluddy** [comment]
An even better question is, why do the XLabels.ml files have any content in them? They should just import X.ml -- OCaml is able to add a labeled interface to a non-labeled module.

**Comment by lostman** [comment]
@bluddy I wasn't aware of that! Just tried it and replacing `ArrayLabels.ml` with
```
include CCArray
```
works nicely.

**Comment by bluddy** [comment]
@lostman exactly. Looking through the commit history, it's possible @c-cube wasn't aware of this feature either.

**Comment by c-cube** [comment]
Thanks for noticing this! It's weird, I'd normally make `CCArrayLabels.ml` a symlink to `CCArray.ml`,  but not here. Note that `_tags` already contains the `nolabel` statement for these files. I suppose the `include` is the cleanest solution.

**Comment by c-cube** [comment]
I'm not very happy with the lack of automation when it comes to keep `Foo.mli` and `FooLabels.mli` in sync. Does anyone have a neat trick for that? 😄

**Comment by lostman** [comment]
Thanks @bluddy for pointing out a cool feature I wasn't aware of!
