### ISSUE TITLE
CCString.lines / CCString.unlines handling of trailing newline

### ISSUE THREAD

**Issue by copy** [c-cube/ocaml-containers#166]
`CCString.{lines,unlines}` treat the newline character like a delimiter between lines, and not a terminator of lines. So there's an extra trailing empty string when using `CCString.lines` and `CCString.unlines` doesn't generate a newline at the end of the string:

```ocaml
CCString.lines "ab\nbc\n";;
(* val _0 : string list = ["ab"; "bc"; ""] *)
CCString.unlines ["ab"; "cd"];;
(* val _3 : string = "ab\ncd" *)
```

I think Haskell got it right:

```
Prelude> lines "ab\ncd\n"
["ab","cd"]
Prelude> unlines ["ab","cd"]
"ab\ncd\n"
```

**Comment by c-cube** [comment]
So it's a bug in `unlines`, it seems. Haskell gives me:

```
ghci> unlines  ["ab","c"]
"ab\nc\n"
ghci> lines "ab\nc"
["ab","c"]
```

**Comment by copy** [comment]
> So it's a bug in unlines, it seems. Haskell gives me:

I think `lines` should also strip the trailing `""` from the list.

**Comment by c-cube** [comment]
Now I'm thinking of offering two optional arguments in split functions:

- `drop_first_if_empty:bool`
- `drop_last_if_empty:bool`

which would respectively do this:

- `split ~drop_first_if_empty:true ~by:" "  " a b c d" = ["a";"b";"c";"d"]`
- `split ~drop_last_if_empty:true ~by:" "  "a b c d " = ["a";"b";"c";"d"]`

instead of also having "" as first (resp. last) element.

Opinions? ping @Drup @copy @bluddy @jpdeplaix @Gbury @struktured

**Comment by Drup** [comment]
That looks like something that is better provided as list/gen combinators.

**Comment by Gbury** [comment]
Having optional arguments for that functionality seems good.
Now for some nitpicking: could the arguments names be shorter (while retaining a clear meaning of course) ? Or an optional argument: ```drop: ([`First_if_empty | `Last_if_empty ] list )``` ?

**Comment by bluddy** [comment]
I think we generally don't want those empty members at the end and beginning -- think about string processing of a file. The default behavior of haskell seems to make sense, and anything else is just over-complicating it IMO. If one needs something so specific, a String.fold is the way to go.

**Comment by c-cube** [comment]
First, I think `lines` and `unlines` should have a fixed semantics (the one proposed by @copy). Otoh, splitting might be more flexible, and I think this belongs in containers, not `gen`, since splitting is already in there.

**Comment by Gbury** [comment]
+1 for List/gen combinators.

In any case, I think the current behavior is good because it allows to distinguish `"ab\ncd"` from `"ab\ncd\n"`.

**Comment by c-cube** [comment]
The problem currently is that, it makes sense for `lines` to add `\n` after each element of the list, but then `"abc\n" |> unlines |> lines` will return `"abc\n\n"`, I think. A full empty line appeared, and this behavior will repeat.

**Comment by jpdeplaix** [comment]
I agree with @bluddy

**Comment by Gbury** [comment]
I think that having ` lines` and `unlines` be inverse of one another is expected given the names, i.e. round tripping should give the identity (if that's not the case, then once giving that would be good, but I'll on my phone so I haven't had the opportunity to test it).
Secondly, when I think about newlines as terminators (rather than separators), then I tend to see `"ab\ncd"` as a badly-specified string since the last one is not terminated.

**Comment by c-cube** [comment]
They can't be perfect inverses, whatever choice we make, but the Haskell choice seems more reasonable.

So given the comments above, I think I'm going to do the following:

- add the optional arguments to `String.Split.*`, keeping them `false` by default (e.g. I see no reason why the first empty "" should be dropped in `split ~by:"-" "-ab-c"`)
- use this new behavior to change how `lines` behaves. `lines s = split ~drop_first_if_empty:false ~drop_last_if_empty:true ~by:"\n" s`, basically.

**Comment by bluddy** [comment]
> add the optional arguments to String.Split.*, keeping them false by default

The main reason for this would be the limitation of the list data structure. A user can easily drop the head of the list if needed, so how about just making an option for the last element?

**Comment by c-cube** [comment]
mostly by symmetry, because it's more convenient (especially with iterators).

**Comment by Drup** [comment]
Well, we can also stop using bad datastructures and stick to gen. :D

**Comment by c-cube** [comment]
Even with `gen`, there's an overhead to dropping the last element :-)
