### ISSUE TITLE
to_string functions in list, array, etc.

### ISSUE THREAD

**Issue by copy** [c-cube/ocaml-containers#167]
The `.pp` functions are useful for printing on a terminal, but sometimes one wants a straightforward string representation, i.e.

```ocaml
val to_string : ?sep:string -> ('a -> string) -> 'a list -> string
```

**Comment by c-cube** [comment]
I tend to do: `CCFormat.(to_string @@ list int)` or something like that.

**Comment by copy** [comment]
> I tend to do: CCFormat.(to_string @@ list int) or something like that.

Nice, TIL. There may still be use-cases for my proposal (it's easier to use for beginners?), but this works for me.

**Comment by bluddy** [comment]
Another TIL here. I always find myself confused when it comes to printers. Would be nice to still have these functions.

**Comment by c-cube** [comment]
Yeah, the types are hard to read :-/
I'll think about the functions. Any volunteer for doing it?
