### ISSUE TITLE
CCStream

### ISSUE THREAD

**Issue by NathanReb** [c-cube/ocaml-containers#172]
I can think about a few handy variations on the standard lib functions such as `get : 'a Stream.t -> 'a option` or `is_empty: 'a Stream.t -> bool` as well as a handful of new ones such as `fold`, `map`, `filter` and so on... Basically anything that's in [Lwt_stream](https://ocsigen.org/lwt/3.1.0/api/Lwt_stream).

Any reason why this is not in `containers` ? If not, is this part of your plans?

If you feel like it would be a worthy addition to the (already great) library, I'd be glad to contribute!

Thanks!

**Comment by Gbury** [comment]
I guess one of the reasons it's not in containers is because there are replacement to `Stream` such as  [gen](https://github.com/c-cube/gen) and [sequence](https://github.com/c-cube/sequence).

**Comment by c-cube** [comment]
Indeed, the reason is I don't use `Stream` and I don't see the point of using it nowadays since I consider the iterators pointed to by @Gbury are better.
