### ISSUE TITLE
CCFormat not compatible with Format?

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#173]
hi, after upgrading to 1.5.1 i get this type error:
```
Error: This expression has type
         (float, 'a) Lacaml.Io.pp_mat =
           Format.formatter ->
           (float, 'a, Bigarray.fortran_layout) Bigarray.Array2.t -> unit
       but an expression was expected of type
         Containers.Format.formatter -> 'b -> unit
       Type Format.formatter is not compatible with type
         Containers.Format.formatter = CCFormat.formatter
```

this is probably trivial but what do i need to fix it? i `open Containers` at the top of the module...

**Comment by nilsbecker** [comment]
`module Format = Containers.Format`? seems weird.

**Comment by nilsbecker** [comment]
i tried rolling back to 1.5 but that was not enough. i got missing functions: `Format.printf` and `Format.of_chan` which were not found after opening containers at the top of the module. in the changelog i did not find the proper way to do this. is `CCFormat` missing an `include Format` somewhere? confused.

**Comment by nilsbecker** [comment]
downgrade to 1.4 works around the issue. at the top of the module i typically have
```
open Containers
open Lacaml.D
```
just in case that's important

**Comment by c-cube** [comment]
I see. Second facepalm for me 🤦‍♂️ 
First I missed a `include Format` in the ml and `include module type of Format` in the mli; second time I clearly missed `… with type formatter = Format.formatter` in the mli.

I'll have to make another release with those.

**Comment by nilsbecker** [comment]
thanks!

**Comment by c-cube** [comment]
https://github.com/ocaml/opam-repository/pull/11166

**Comment by c-cube** [comment]
Does 1.5.2 solve the issue for you?

**Comment by nilsbecker** [comment]
it seems to be working now, yes, thanks!
