### ISSUE TITLE
Rename CCChar.pp / CCChar.print

### ISSUE THREAD

**Issue by Fourchaux** [c-cube/ocaml-containers#181]
The names _CCChar.pp_ & _CCChar.print_ seem wrong.

Should be _CCChar.pp_buf_ & _CCChar.pp_ 
(see CCString).

- [ ] rename `CCChar.pp`
- [ ] rename `CCHeap.print`

**Comment by c-cube** [comment]
Where do you see that? In doc? You'll probably want to compile a list of changes because this kind of discrepancy might be everywhere…

**Comment by Fourchaux** [comment]
Ah yes, in the sources 
see https://github.com/c-cube/ocaml-containers/blob/master/src/core/CCChar.ml#L11
and https://github.com/c-cube/ocaml-containers/blob/master/src/core/CCChar.mli#L43

**Comment by c-cube** [comment]
Oh… so I forgot to update this? 😢

**Comment by c-cube** [comment]
Good catch, thank you.

**Comment by Fourchaux** [comment]
Remark:

Now, all the printing functions are called **pp** or **pp_foo** EXCEPT one:

https://github.com/c-cube/ocaml-containers/blob/master/src/core/CCHeap.ml#L177
https://github.com/c-cube/ocaml-containers/blob/master/src/core/CCHeap.mli#L113

To be renamed **pp** maybe ?

**Comment by c-cube** [comment]
good catch (bis)
