### ISSUE TITLE
Add minimum versions for depenencies in OPAM package

### ISSUE THREAD

**Issue by reubenrowe** [c-cube/ocaml-containers#188]
Is it possible to add minimum versions for the dependencies to the OPAM package?

For a particular reason, I am pinning to jbuilder1.0+beta11, but version 2.0 of containers will not build with this. OPAM happily tries to do so, however.

**Comment by c-cube** [comment]
which part fails to build? Tests do need a recent jbuilder (because of --force), otherwise I don't know any problem.

Note that jbuilder1.0+beta11 is going to be superior to jbuilder1.0 for opam, so upper bounds will not cut it 😞

**Comment by jpdeplaix** [comment]
> Note that jbuilder1.0+beta11 is going to be superior to jbuilder1.0 for opam, so lower bounds will not cut it 😞

The trick here is that there will be no ```jbuilder.1.0``` but rather ```dune.1.0``` ^^"

**Comment by reubenrowe** [comment]
jbuilder1.0+beta11 doesn't recognise the `(fallback)` field in the jbuild file:

```
File "src/jbuild", line 6, characters 4-12:
Error: Unknown field fallback
```

**Comment by reubenrowe** [comment]
If there is not a way for OPAM to reference subversions (as it were), then feel free to close this issue - I can always pin containers to 1.5.2.

**Comment by c-cube** [comment]
I think it's simpler indeed to pin, sorry.
