### ISSUE TITLE
Don't optionalize IntXX.of_int

### ISSUE THREAD

**Issue by madroach** [c-cube/ocaml-containers#192]
Hi,

the ``Int{32,64}.of_int`` functions don't fail (except for Out_of_memory).
Why then was ``of_int_exn`` added and ``of_int`` changed to return an option?
Please tell me if I'm mistaken. Otherwise I'd suggest deprecating the ``of_int_exn`` functions and a breaking change to the ``of_int`` functions.

**Comment by c-cube** [comment]
That's… a good question. I thought it was like `of_string`, which fails if the string represents too big an integer, but `of_string` is the only function that fails, it seems. Thanks for pointing this out.
