### ISSUE TITLE
Labels need some care

### ISSUE THREAD

**Issue by madroach** [c-cube/ocaml-containers#193]
Hi,

at least ``ArrayLabels`` is out of sync with ``Array``.
Maybe it is time to consider how labelizing a module is supposed to work.
Batteries for example adds a ``M.Labels`` to the modules needing labelized functions and requires to open them with something like
```
module Array = struct include Array include Array.Labels end
```
In contrast the Stdlib has the seperated ``ArrayLabels``, ``ListLabels``, ``StringLabels`` ... and the ``StdLabels`` and ``MoreLabels`` to open them all at once.

**Comment by c-cube** [comment]
Ah, keeping them in sync is painful, I still don't have a good solution for that. But I don't like the batteries solution (makes for much bigger modules), so containers follows the stdlib' style.

**Comment by madroach** [comment]
I may have some spare time in March. Would a pull request syncing the labeled modules and adding missing labeled modules be included?

**Comment by c-cube** [comment]
A PR is always welcome (even if I don't merge it). Syncing the labeled modules would certainly be merged, yes! Regarding stdlabels and morelabels, I don't have a strong opinion (I don't use these) but it could be a small part of `Containers.ml`, as in:

```ocaml
module StdLabels = struct
  module Array = CCArrayLabels
  module List = CCListLabels
end
```
