### ISSUE TITLE
Add Infix comparison operators for Bool, String, Char, Int64, Int32, Nativeint

### ISSUE THREAD

**Issue by bluddy** [c-cube/ocaml-containers#198]
* The case is strongest for string, char and bool, but useful for others.
* Also, Int32 and Nativeint need a module.
* Bool, String: (=, <>)
* Char, Int64, Int32, Nativeint: (<, >, =, <>, <=, >=)
* Should strings get lexicographical comparisons as Infix operators? Not sure. This may be a more 'advanced' function requiring compare.

**Comment by c-cube** [comment]
regarding lexicographic compare for strings: I don't think it deserves an infix operator. Better use the explicit name that will not require people who read the code to look them up in the doc.

For the rest: good points. I'm not really motivated to write `Int32` and `Nativeint` right now, but if someone volunteers…

**Comment by c-cube** [comment]
I think this has made good progress! It should be ready soon I think.
