### ISSUE TITLE
merlin locate?

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#199]
I get this (e.g.)
```
'List.filter_map' seems to originate from 'CCList' whose ML file could not be found
```
when i try to locate the definition of a containers-defined function. is there a way to allow this using the new build infrastructure?

**Comment by jpdeplaix** [comment]
Does this happens with containers 2.0 or an older version ?

**Comment by c-cube** [comment]
So, the issue seems to be that jbuilder doesn't install source files, only .mli files.

**Comment by bluddy** [comment]
Or is the issue with merlin not defaulting to .mli wiles when .ml files aren't found?

**Comment by nilsbecker** [comment]
this is with containers 2.0 fwiw.

**Comment by nilsbecker** [comment]
having the implementations available quickly is not a must-have i would say. but sometimes it could be handy or educational as well.

**Comment by jpdeplaix** [comment]
So I believe it's definitely something that could be improved in merlin so I opened an issue there.
Now, jbulider+beta18 will install .ml files so this should be fixed as soon as it is released, at least for containers.

**Comment by Fourchaux** [comment]
This (huge) PR for 4.06 https://github.com/ocaml/merlin/commit/85946fec4573d0fdbbce92e5b395f6bcc582208f
solves the problem, I think.
