### ISSUE TITLE
#require "containers.top" tries to install outdated printers.

### ISSUE THREAD

**Issue by vrotaru** [c-cube/ocaml-containers#201]
Here's the relevant part in [contaners_top.ml](https://github.com/c-cube/ocaml-containers/blob/a0d0cf9d88e0857853606761557d2ea617055ecc/src/top/containers_top.ml#L18)
```OCaml
let () =
  install_printers
    [ "CCHashtbl.print"
    ; "CCBV.print"
    ; "CCDeque.print"
    ; "CCFQueue.print"
    ; "CCIntMap.print"
    ; "CCPersistentArray.print"
    ; "CCSexp.pp"
    ]
```

Replacing the `print` with `pp` should fix the issue.

And I guess it slipped through, because the compiler did not complain.

**Comment by c-cube** [comment]
The compiler probably loads these in silent mode or whatever. Thank you for the report.

**Comment by vrotaru** [comment]
The problem here is that for compiler those are just list of strings.

Maybe a test is possible or this file should be dropped and the module can have something like this at the end
```OCaml
let () = if !Sys.interactive then install_printer pp else ()
```
But there can be reasons to keep it separate. Can't say at the moment

**Comment by c-cube** [comment]
I'm not in favor of having this in the core library, because:

- it depends on `compiler-libs.common`
- installing printers silently feels wrong (too implicit).
