### ISSUE TITLE
CCRal.take_drop bug

### ISSUE THREAD

**Issue by rand00** [c-cube/ocaml-containers#208]
There is a bug in `take_drop` - which just calls `take` and `drop`, so should be `drop` that has a bug; 
``` ocaml
include CCRAL

let log = Printf.printf

let p v n =
  log "%s: " n;
  iter (log "%d ") v;
  log "\n"

let _ =
  let v = of_list [1;2;3;4;5;6;7;8;9;10;11;12] in
  p v "v initial"; log "\n";
  let vl, vr = take_drop 5 v in
  p vl "vl"; p vr "vr"; log "\n";
  let vm, vr = take_drop 4 vr in
  p vm "vm"; p vr "vr"; log "\n"
```  
Which prints
```
v initial: 1 2 3 4 5 6 7 8 9 10 11 12 

vl: 1 2 3 4 5 
vr: 6 7 8 9 10 11 12 

vm: 6 7 8 9 
vr: 
```
Will take a look at it

**Comment by c-cube** [comment]
What version of containers do you have? On 2.0 I get:

```
v initial: 1 2 3 4 5 6 7 8 9 10 11 12 

vl: 1 2 3 4 5 
vr: 6 7 8 9 10 11 12 

vm: 6 7 8 9 
vr: 10 11 12 
```

There was a bugfix related to that in 2.0, reported in #184. You're probably experiencing the same.

Please re-open if you're on 2.0 and the bug persists.

**Comment by rand00** [comment]
Yes I am on 2.0+alpha2 - weird that you get different results.. I reported the last issue, so yes I know (:

**Comment by c-cube** [comment]
Ah, try with 2.0 (the fix was after alpha2)!

**Comment by rand00** [comment]
Ah silly... Howcome opam sees it as a downgrade?

**Comment by rand00** [comment]
Found out : https://opam.ocaml.org/doc/FAQ.html#How-does-OPAM-tell-which-version-of-a-package-is-newer

**Comment by rand00** [comment]
~ should be used for alpha etc. instead of +

**Comment by rand00** [comment]
But yes, v. 2.0 works for me too

**Comment by c-cube** [comment]
Yeah, I know about `~`, but opam-publish rejects it so at first I thought it was wrong. Normally alpha{1,2} should not be in opam-repo anymore but there's an [issue on opam-repo](https://github.com/ocaml/opam-repository/issues/11506) right now.

**Comment by rand00** [comment]
Hehe - a fine range of causes of why I thought there was still a bug (;
