### ISSUE TITLE
monad-building functor

### ISSUE THREAD

**Issue by c-cube** [c-cube/ocaml-containers#21]
In `containers.advanced`, a functor

``` ocaml
module MakeMonad(M : sig
  type 'a t
  val return : 'a -> 'a t 
  val (>>=) : 'a t -> ('a -> 'b t) -> 'b t
  val map : [`Redefine | `Use of ('a t -> ('a -> 'b) -> 'b t)]
  (* etc. for other optional values *)
end) : sig
  (* copy monad stuff *)
  (* add applicative stuff *)
  (* add some sequence operators? *)
end
```

**Comment by kwshi** [comment]
Would it be nice to also have an applicative-building functor (or is there already one)?

**Comment by c-cube** [comment]
I think neither is actually useful in OCaml. It's bad for performance and really, if you use a monad you can write your own applicative and bind anyway :-).
