### ISSUE TITLE
CCList refers to Standard Library Random module instead of Containers Random module

### ISSUE THREAD

**Issue by reubenrowe** [c-cube/ocaml-containers#210]
Running the following in the OCaml toplevel
```
#use "topfind" ;;
#require "containers" ;;
open Containers ;;
List.random_choose [1;2;3] (Random.get_state()) ;;
```
results in the following error:
```
Error: This expression has type Containers.Random.State.t = CCRandom.State.t
       but an expression was expected of type Random.State.t
```
where `This expression` is referring to `Random.get_state()`.

The definition of `random_gen` in the List module refers to the standard library `Random` module, but wouldn't it be better for it to refer to `CCRandom`? Otherwise, one has to bind the standard library `Random` module before opening `Containers`.

**Comment by hcarty** [comment]
This looks like a missing type equivalence for `CCRandom.State.t`.  It should be exactly equivalent to `Random.State.t` from the OCaml stdlib.  Good find @reubenrowe

**Comment by reubenrowe** [comment]
It could be that `CCRandom.mli` needs to use
```
include module type of struct include Random end
```
instead of
```
include module type of Random
```
on [line 6](https://github.com/c-cube/ocaml-containers/blob/f07cae6c82807ea1b415cfcecb2f634b3dc57e2f/src/core/CCRandom.mli#L6).

I remember asking Leo White at Jane Street why their code uses the more complex idiom for module type extraction and he said it was because you do not get module type equivalences with the simpler form.

**Comment by c-cube** [comment]
Good catch indeed. I found about this trick quite recently (thanks to @Drup) and I need to migrate the includes to it. Thanks for the report!
