### ISSUE TITLE
Have a containerLabels module

### ISSUE THREAD

**Issue by bluddy** [c-cube/ocaml-containers#216]
The StdLabels module opens the stdlib with labelled modules as the default. It would be nice to allow the same functionality with Containers.

**Comment by madroach** [comment]
Given a labelled module interface, could one not automatically generate a non-labelled version of it by simply dropping all labels?
Not as simple, but still not too difficult would be the task of generating a non-labelled implementation file out of the labelled interface file.

Given this interface and implementation
``` ocaml
module type CCArrayLabels = sig
  val make : int -> 'a -> 'a array
  val get : 'a array -> int -> 'a
  val set : 'a array -> int -> 'a -> unit
  val fill : 'a array -> pos:int -> len:int -> 'a -> unit
end
module CCArrayLabels :CCArrayLabels = ArrayLabels
```
the task would be to generate this interface and implementation:
``` ocaml
module type CCArray = sig
  val make : int -> 'a -> 'a array
  val get : 'a array -> int -> 'a
  val set : 'a array -> int -> 'a -> unit
  val fill : 'a array -> int -> int -> 'a -> unit
end

module CCArray : CCArray = struct
  open CCArrayLabels
  let make = make
  let get = get
  let set = set
  let fill a b c d = fill a ~pos:b ~len:c d
end
```

Looks like its easily scriptable to me or am I missing something?

**Comment by c-cube** [comment]
I'm not sure it's so easy to script. Also, even in non-label modules, there are some labels when we're not tied by retrocompat.

**Comment by madroach** [comment]
What would be the preferred layout of interfaces?
* ``Array.Labels``
* ``ArrayLabels``
* ``Labels.Array``
* ``Containers.Labels``
* other ?

**Comment by madroach** [comment]
So if I manage to hack up some script would this be considered for inclusion and the obvious modules be labelled?

**Comment by c-cube** [comment]
Another problem is the docstrings, where there are code samples like `Foo.map f l` instead of `Foo.map ~f l`. I'm also feeling a bit uneasy removing things like `CCList.mli` and have them autogenerated…

**Comment by madroach** [comment]
#227 implements my suggestion to autogenerate unlabelled interfaces.
It automatically fixes the docstrings.

**Comment by c-cube** [comment]
so maybe now we can do something like a `containersLabels.ml` file with:

```ocaml
include Containers
module String = CCStringLabels
module Array = CCArrayLabels
(* … *)
```
What do y'all think?

**Comment by c-cube** [comment]
Why not `containers.ml` and `containersLabels.ml` as separated files (with the second one including the first one and then overloading some modules)? That'd be more "pay for what you use" since no module would be created inside, only module aliases.

**Comment by madroach** [comment]
Its just that I like a ``Containers.Labels`` notation better than ``ContainersLabels``. But nevermind that's just my preference.
Nevertheless and unrelated overloading won't work since module names can't be redefined.

**Comment by madroach** [comment]
One could always add
``` ocaml
module Labels = CCArrayLabels
```
to ``containers.ml``
