### ISSUE TITLE
NaN with functions CCFloat.min & CCFloat.max

### ISSUE THREAD

**Issue by Fourchaux** [c-cube/ocaml-containers#220]
Concerning Float.min/Float.max, the behavior of several languages (SML, Rust, also Base) is:

- If one of the arguments is nan, then the other argument is returned.
- If both arguments are nan, then nan is returned.

So, I think, CCFloat.min & CCFloat.max should rather be written:

```ocaml
let min (x : t) y =
  if is_nan y then x
  else if is_nan x then y
else if x < y then x else y

let max (x : t) y =
  if is_nan y then x
  else if is_nan x then y
else if x > y then x else y
```

**Comment by c-cube** [comment]
Is there a compelling argument about that, like a rust RFC?
For me it's natural that `min x y <= x` and `min x y <= y`, which is not the case with `nan`.

**Comment by Fourchaux** [comment]
Here https://en.wikipedia.org/wiki/IEEE_754_revision#min_and_max
 
we have:
- min(x,NaN) = min(NaN,x) = x
- max(x,NaN) = max(NaN,x) = x

**Comment by c-cube** [comment]
I changed so that `min x nan = x` and `max x nan = x` :-)
