### ISSUE TITLE
CCUnix.call'ed process are not killed when the caller is

### ISSUE THREAD

**Issue by grayswandyr** [c-cube/ocaml-containers#221]
...or so it seems. 
I use CCUnix.call to run a process, but when the parent (calling CCUnix.call) is killed, the child process remains running. As CCUnix.call does not return the child's PID, I can't even kill it from the parent.
Any idea?

**Comment by c-cube** [comment]
Maybe the PID can be added to the result of `call_full`, without breaking compatibility. I'm not sure whether the underlying `Unix` API I use allows that, but that'd be the good way I think

As a workaround, have you considered `Unix.setsid` so that the caller becomes a session leader?

**Comment by c-cube** [comment]
I'm not sure we can really do better from containers itself; if the caller dies it can't use the pid anyway.

**Comment by grayswandyr** [comment]
Thanks for the info. IIUC you use setsid not so much for terminal detaching but to create a process group such that killing the parent (the one who made the setsid call) will also kill children of the same group?

Concerning the last remark, if the parent holds its child PID and receives a SIGTERM, it would be able to handle this signal to kill its child before killing itself, right? This part is out of containers itself, but returning the PID is not.

**Comment by c-cube** [comment]
Indeed, the children's fate is tied to the session leader, which is why `setsid` is useful.

I'm not used to handling signals, but that's a good point. Maybe something we need in containers is a local signal handler:

```ocaml
val with_sig_handler: (signal -> unit) -> (unit -> 'a) -> 'a
```

Tell me what you think...

**Comment by grayswandyr** [comment]
According to a colleague who tried my program updated with your `setsid` example, it seems it's not working under MacOS.

Concerning your local signal handler, you mean you would install a signal in the scope of the second argument, and then reset it outside, right? If so, I find this nice indeed. I think that some thinking is needed, though: if you intercept SIGTERM for instance, it's certainly because you want to free resources such as file descriptors, so I think some solutions are easier than others here. I seem to remember that the [OCaml Unix systems programming manual](https://ocaml.github.io/ocamlunix/index.html) suggests, for instance, to catch the signal and raise an exception.

**Comment by c-cube** [comment]
I try to minimize the amount of unix programming I do, so such features would have to be contributed by someone else anyway. Regarding `setsid` on mac OS, well… sorry :man_shrugging:

**Comment by bluddy** [comment]
Is there a good cross-platform Process library?

**Comment by c-cube** [comment]
It's called `Lwt_process` :innocent:
