### ISSUE TITLE
Equal.always and .never

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#232]
when combining equalities for a pair or values recently i wished i had
`Equal.always = fun _ _ -> true`. would it make sense to add that, and it's opposite?

**Comment by c-cube** [comment]
Why not, maybe with a more explicit name (`always_equal`? hmm). The negation is pretty weird though, because it violates reflexivity (`x = x`).

**Comment by nilsbecker** [comment]
fair point about the reflexivity. that would be the behavior of NaN. but for instance in the context of the react FRP library, where an equality function is used to check whether a signal has changed at a given update step, such a `never` function would make sense. not sure if that's worth accepting the ugliness. about the name, i think that Equal already has function names that are only understandable in the context of the module name `Equal`; `always` would be no different.

**Comment by c-cube** [comment]
I guess. Would you be willing to make a PR? :)

**Comment by nilsbecker** [comment]
i'll see how far i get...
