### ISSUE TITLE
CCRingBuffer / CCVector keeps deleted values alive

### ISSUE THREAD

**Issue by copy** [c-cube/ocaml-containers#235]
I'm using a `CCRingBuffer` as a buffer for packets coming from a network to process them later. Typically there is not more than one packet in the buffer and they arrive and are consumed in regular time intervals.

The consuming functions of `CCRingBuffer` ([`take_front_exn`](https://github.com/c-cube/ocaml-containers/blob/2a97950/src/data/CCRingBuffer.ml#L367), etc.) don't overwrite the removed element in the underlying array, so the deleted value is kept alive (from the point of view of the garbage collector). Even worse, with my use case, the deleted values are often promoted to the major heap.

This also applies to `CCVector`.

I have observed this using statmemprof.

Base seems to do this correctly: https://github.com/janestreet/base/blob/209e74b/src/queue.ml#L216

**Comment by c-cube** [comment]
That makes sense. I've just started a branch (`wip-235`) for that, at least for `Vector`, addressing the issue by copying the first element in place of the removed ones. However the first element won't be free'd ever unless the vector itself is (we may add `val free: _ t -> unit` that behaves like `clear` but also kills the array).

For the circular buffer I suppose we should just put the `dummy` element in place of the removed elements. Would you be willing to help on that?

**Comment by copy** [comment]
> Would you be willing to help on that?

Yep, I'll take care of it.

**Comment by c-cube** [comment]
Please do it on top of my branch then :)
Some additional tests would also be good (`Gc.major()` + `Weak` can be used to check whether something has been GC'd)
