### ISSUE TITLE
Rounding mode of CCFloat.round

### ISSUE THREAD

**Issue by quicquid** [c-cube/ocaml-containers#237]
It seems the rounding mode of CCFloat is to round half-way down:

    utop # CCFloat.round (- 1.5) ;;
    - : float = -2.
    utop # CCFloat.round ( 1.5) ;;
    - : float = 1.

Is this intended behaviour? In any case, it might be good to document which rounding mode is used.

**Comment by nilsbecker** [comment]
or possibly provide other rounding modes as well?

**Comment by c-cube** [comment]
I don't think OCaml gives control over the underlying rounding mode, so providing other modes is totally out of scope. Documenting the current behavior is still a good idea!

**Comment by nilsbecker** [comment]
There may be a clash with the `Float` module in 4.07+. That module has `round` which rounds away from 0, which is *different* from `CCFloat.round`. The docs talk about a "current rounding direction" which sounds like there is a stateful switch to change the rounding behavior. I have not found another mention of that switch in the `Float` docs, which i find confusing.

**Comment by Gbury** [comment]
I think you can change the rounding only from C code (see ocaml/ocaml#7890 and ocaml/ocaml#3526 )
