### ISSUE TITLE
the logo doesn't look like a tough container

### ISSUE THREAD

**Issue by UnixJunkie** [c-cube/ocaml-containers#240]
"From WordNet (r) 3.0 (2006) [wn]:

  container
      n 1: any object that can be used to hold things (especially a
           large metal boxlike object of standardized dimensions that
           can be loaded from one form of transport to another)
"

**Comment by UnixJunkie** [comment]
For example, this image
http://www.container-z.com/uploads/files/image-site1route-15.jpg
shows a tough container.
Something that you can probably rely on.

**Comment by UnixJunkie** [comment]
This one also doesn't look bad:
https://www.free-emoticons.com/files/transport-emoticons/14064.png

**Comment by UnixJunkie** [comment]
Maybe this style is even better to illustrate modularity, in some way:
https://www.catholicfoundationgb.org/wp-content/uploads/2016/04/RedShippingContainerWEB-300x187.jpg

**Comment by UnixJunkie** [comment]
Yes, a cardboard box is a rather fragile container, that doesn't last very long as far as my experience can tell.
I don't think this is a good image to illustrate some OCaml software.

**Comment by c-cube** [comment]
Is this serious? :man_facepalming: 
I mean, if you assess the reliability of software based on emojis in their readme, I hope you took some sunscreen to use OCaml, your trusted can of octopus repellent for any github software, and a deep breath before diving into ocsigen's doc…

**Comment by UnixJunkie** [comment]
I thought this emoji is the real logo of the software. I am serious, but you can close the issue if you feel it doesn't matter.
