### ISSUE TITLE
CCFun_vec.pop_exn: Assert_failure

### ISSUE THREAD

**Issue by copy** [c-cube/ocaml-containers#241]
`CCFun_vec.pop_exn` seems to take the `_exn` part seriously and fails on every vector, for example:

```
utop [6]: CCFun_vec.(pop_exn @@ of_list [1]);;
Exception: Assert_failure ("src/data/CCFun_vec.ml", 221, 6).
```

**Comment by c-cube** [comment]
Heh, it's labelled as "experimental, do not use". But good catch.
