### ISSUE TITLE
CCHashtbl.pp line breaks

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#243]
i get outputs like this:
```
adding-congestion events by reaction: tbl {
                                        {id 4, B+A→C, k=10.00, rid 5} -> 1098
                                        , {id 5, C→B+A, k=47.00, rid 4} -> 307
                                        }
```
here, the output starting from tbl is formatted by `Hashtbl.pp` with a custom key and int values. i find the placement of the comma weird; is this the intended line breaking?

**Comment by c-cube** [comment]
It's not really intended, we could change it, I think. I tend to mostly use `CCFormat.seq`, in practice.
