### ISSUE TITLE
safe version of Array.random_choose

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#246]
`Array.random_choose [||]` gives a random generator that always raises `Not_found`. it would be nice to have an option type returning function that gives `None` for empty arrays and `Some gen` for non-empty array, with a generator that returns values.

**Comment by c-cube** [comment]
I'm not sure what use case there is for a combinator that might not return a generator? In any monadic context it'll not work, right?

**Comment by hcarty** [comment]
Would it be better to have `random_choose` raise `Invalid_argument` when the array is empty?

**Comment by c-cube** [comment]
It seems orthogonal to me, @hcarty, but that's definitely a good idea (same for lists if not already the case).

**Comment by nilsbecker** [comment]
ok, raising on creation might be better. i thought what i proposed was probably more useful than a generator that returns `'a option` depending on whether the underlying array is empty. but raising early seems ok.
