### ISSUE TITLE
avoid ligatures in web docs

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#247]
the nicely formatted doc pages show infix operators with fancy ligatures -- this is not ideal since it's not always clear how to type them!

**Comment by c-cube** [comment]
Please open an issue with https://github.com/ocaml/odoc , I won't do anything to change its output :)

**Comment by nilsbecker** [comment]
ok!

**Comment by nilsbecker** [comment]
it seems this is already resolved upstream. https://github.com/ocaml/odoc/issues/248#issue-381787861
