### ISSUE TITLE
printer installation for ocamldebug requires loading containers_monomorphic

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#248]
printer installation in ocamldebug is always a tedious business, since one has to load the whole dependency tree of libraries by hand. i recently noticed that loading containers directly fails -- it is necessary to use the sequence
```
load_printer containers_monomorphic.cma
load_printer containers.cma
```
this is not ideal since finding the right archive `containers_monomorphic` to load requires digging in the opam directory. i don't know what the best remedy is. another module dependency structure? documentation?

**Comment by c-cube** [comment]
I don't know either, but changing the module dependency structure is quite unlikely.

**Comment by nilsbecker** [comment]
as the use of ocamldebug does not seem very widespread, it's probably best to only add a findable doc section for users who do need it. that said, i think a big part of the reason that ocamldebug is not used more is precisely the hassle with getting readable printing for user types

**Comment by c-cube** [comment]
Could you contribute a small paragraph in the readme? I indeed don't use ocamldebug (I never remember how to use it, and it requires bytecode, which is slow).

**Comment by nilsbecker** [comment]
that should be doable.
