### ISSUE TITLE
add 'tap' infix operator?

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#255]
i'm thinking of this, which i find handy when chaining data transformations to insert e.g. a print statement.
```ocaml
let (|-) (f: 'a -> unit) x = (f x; x)
```
this is easy enough to define but it seems that a standardized syntax in containers could help to make its usage uniform and readable by others? could of course be a bad idea or could exist already?
also, the syntax is debatable. it should ideally indicate that the data stream is 'tapped' to do something effectful but otherwise continues.

**Comment by Gbury** [comment]
It looks like [CCFun.tap](http://c-cube.github.io/ocaml-containers/last/containers/CCFun/index.html#val-tap), which can be used in pipes:
```ocaml
x
|> some_fun
|> CCFun.tap print_fn
|> some_other_fun
```

**Comment by nilsbecker** [comment]
hmm, so it would be basically an infix notation for `CCFun.tap` i guess. ah and i mixed it up!
```ocaml
let (|-) x (f: `a -> unit) = (f x;x)
```
which may be the same as `let (|-) = CCFun.tap` ...

**Comment by nilsbecker** [comment]
actually, `let (|-) x f = CCFun.tap f x` except for the slightly more restrictive type. but that restrictiveness could be left up to the compiler. so all in all it would just be a standard infix notation

**Comment by nilsbecker** [comment]
but then, maybe it's not generally useful enough and the explicit notation is better!?

**Comment by Gbury** [comment]
Well, I'm not convinced it deserves an infix operator, since it's already easy to write using `|>` and `CCFun.tap`. Moreover, too many infix operators can really make code much harder to read and write, for instance [this code](https://github.com/Gbury/archsat/blob/master/src/main.ml#L103-L112) I wrote some time ago is pretty neat, but can be a real pain to update, ^^

**Comment by nilsbecker** [comment]
@Gbury you could have opened `Pipe` locally ;)

**Comment by Gbury** [comment]
Yeah, but `Pipeline` was already opened locally (though ~20 lines above), and multiple local opens really make it hard to see where a value comes from.
Anyway, I don't know if adding an infix operator would really help with readability.

**Comment by nilsbecker** [comment]
yes, it was partly meant as a joke. anyway, if there is consensus that this is not worth it, this issue should be probably closed. i guess if infix operators were allowed more verbose names including characters, it would be a different story. `a |tap> print_it |> f` or something like that. but that's just fantasy.

**Comment by c-cube** [comment]
Thanks for the proposal @nilsbecker. I think that indeed `|> CCFun.tap foo` is simpler, and it also makes it clearer (to me at least) that the precedence is the same, whereas in `x |> f |- g |> h` I'd be a bit worried what `|> h` applies to. Closing this, but if you feel strongly about it please reopen :)
