### ISSUE TITLE
Error while installing Containers with 4.08.0+flambda

### ISSUE THREAD

**Issue by Fourchaux** [c-cube/ocaml-containers#262]
For info:
```
#=== ERROR while compiling containers.2.5 =====================================#
# context     2.0.4 | linux/x86_64 | ocaml-variants.4.08.0+flambda | 
...
# If you need to stay compatible with OCaml < 4.07, you can use the 
# stdlib-shims library: https://github.com/ocaml/stdlib-shims
# File "src/core/CCParse.ml", line 143, characters 34-48:
# 143 | let string_equal (a : string) b = Pervasives.(=) a b
#                                         ^^^^^^^^^^^^^^
# Alert deprecated: module Stdlib.Pervasives
# Use Stdlib instead.
```

**Comment by c-cube** [comment]
I know, there's a branch to compile properly on  4.08. Blame the deprecations :p

**Comment by Gbury** [comment]
The deprecation should only be a warning though, so it shouldn't make the build error (in an ideal world, ^^), or am I missing something ?

**Comment by c-cube** [comment]
It's not just the deprecations actually, it's also that new `type 'a t = 'a array` and `type 'a t = 'a list` have appeared and clash with the existing definitions in containers. The new branch addresses that.

**Comment by c-cube** [comment]
is this still happening?

**Comment by Fourchaux** [comment]
Installing Containers 2.6.1 (opam version or dev version) is now OK.
😊
