### ISSUE TITLE
CCChar not used

### ISSUE THREAD

**Issue by cemerick** [c-cube/ocaml-containers#281]
`containers.ml` doesn't use `CCChar`:

https://github.com/c-cube/ocaml-containers/blob/70bd7f1e97bf278fadc17787c313ac34722a7ba7/src/core/containers.ml#L9

I would think this is an oversight, but it's been like that for two years....

**Comment by c-cube** [comment]
Ah, I don't personally use `open Containers` so I tend to directly call `CCChar`. This is just an oversight indeed.
