### ISSUE TITLE
introducing fold_until convenience function

### ISSUE THREAD

**Issue by struktured** [c-cube/ocaml-containers#29]
Option 1:

```
let rec fold_until (f: 'b -> 'a -> 'b * bool) (acc:'b) = 
  function | [] -> acc | e::l -> let acc, cont = f acc e in if not cont then acc else 
   fold_until f acc l;;
val fold_until : ('b -> 'a -> 'b * bool) -> 'b -> 'a list -> 'b = <fun>                                                                             
```

Pros: can accumulate and terminate on last step.
Cons: more complicated return value of the accumulator function

Option 2:
```
 let rec fold_until (f: 'b -> 'a -> 'b option) (acc:'b) = 
   function | [] -> acc  
   | e::l -> match f acc e with None -> acc | Some acc -> fold_until f acc l;;
val fold_until : ('b -> 'a -> 'b option) -> 'b -> 'a list -> 'b = <fun>                                                                             
```

Pros: simple accumulator with use of options
Cons: can't accumulate on last step

In either case, I would like to add this function to CCList, CCArray, Gen, and where-ever else it makes sense. So, do you think this function merits an addition to the library? And which signature do you prefer?

**Comment by struktured** [comment]
Perhaps fold_while is a better name, as it matches take_while and fits better with the boolean's semantic meaning as well.

**Comment by c-cube** [comment]
I think this can be useful, indeed (in particular in sequence and gen, which are separate libraries; sequence is compatible with most structures in containers and even other libraries). I don't like much the first option, it's not clear from the type whether `true` means "stop" or "continue".

I suggest something along the lines of:

```ocaml
val fold_while: ('a -> 'b -> 'a * [`Stop | `Continue]) -> 'a -> 'b t -> 'a
```

it could be nice in `CCList`, `CCArray`, gen and sequence, I believe. In other modules it's a bit too specific, especially if it's already in sequence.

Thanks for the proposal!

**Comment by struktured** [comment]
Did you mean this?
```
val fold_while: ('a -> 'b -> 'b * [`Stop | `Continue]) -> 'b -> 'a t -> 'b
```

**Comment by c-cube** [comment]
No, the previous one, à la `List.fold_left` (or `Array.fold_left`, etc.). You can also use more descriptive names, like:

```ocaml
val fold_while : ('acc -> 'elem -> 'acc * [`Stop | `Continue]) -> 'acc -> 'elem t -> 'acc
```
```
