### ISSUE TITLE
list of breaking changes for 3.0

### ISSUE THREAD

**Issue by c-cube** [c-cube/ocaml-containers#290]
- [x] remove `String.Sub` and `Array_slice` from the core
- [x] harmonize some `?eq` and `~eq` parameters
- [x] make containers.data into its own package
- [x] remove deprecated methods, including the ones referring to "sequence"
- [x] migrate CCKList into CCSeq, an extension of standard Seq

please contribute other (small) changes you'd like to see, so we can discuss them!

- [x] harmonize CCList.mem and CCArray.mem
- ~~[ ] promote CCDeque in containers~~
- [x] CCVector.remove renamed to CCVector.remove_unordered
- [x] Rename CCVector.shrink
- [x] Change all formatters/printers to take `Format.formatter -> unit -> unit` arguments rather than `string` for wrappers and separators (see https://github.com/c-cube/ocaml-containers/issues/295#issuecomment-606448697)
- [x] Update all `seq`/`sequence` to use `Stdlib.Seq` and convert existing definitions to `Iter`
- [x] harmonize all `of_string`/`of_string_opt` with stdlib's signatures (in int32/int64) and with one another (#303 )

**Comment by FardaleM** [comment]
- harmonize CCList.mem and CCArray.mem

**Comment by orbitz** [comment]
- `CCVector.remove` renamed to `CCVector.remove_unordered`.

**Comment by FardaleM** [comment]
>     * `CCList.mem` not taking an instance (or maybe this is a different function).  I want to be able to do `CCList.mem ~eq:(fun (_, v) -> v = smth) list`.
This is call `CCList.exists`

**Comment by hcarty** [comment]
* Change all formatters/printers to take `Format.formatter -> unit -> unit` arguments rather than `string` for wrappers and separators (see https://github.com/c-cube/ocaml-containers/issues/295#issuecomment-606448697)
* Update all `seq`/`sequence` to use `Stdlib.Seq` and convert existing definitions to `Iter`

**Comment by c-cube** [comment]
>     * Update all `seq`/`sequence` to use `Stdlib.Seq` and convert existing definitions to `Iter`

@hcarty this has been started, with the deprecation of existing `_{to,of}_seq`. It will not be possible for all cases (Map/Set/Hashtbl are opaque) but it can definitely be more uniform.

**Comment by Fourchaux** [comment]
Here is a diff on the interfaces for CCInt and CCInt32_CCInt64_CCNativeint :
```ocaml
(*------ Not in CCInt ------*)
  CC{Int32|Int64|Nativeint}.abs : t -> t
  CC{Int32|Int64|Nativeint}.max_int : t -> t
  CC{Int32|Int64|Nativeint}.min_int : t -> t
  CC{Int32|Int64|Nativeint}.to_float : t -> float
  CC{Int32|Int64|Nativeint}.of_string_opt : string -> t option ;;
  
(*------ Not in CCInt32_CCInt64_CCNativeint ------*)
  CCInt.sign : t -> int
  CCInt.pow : t -> t -> t
  CCInt.floor_div : t -> t -> t

  CCInt.random : int -> t random_gen
  CCInt.random_small : t random_gen
  CCInt.random_range : int -> int -> t random_gen

  CCInt.pp : t printer

  CCInt.pp_binary : t printer
  CCInt.to_string_binary : t -> string

  CCInt.min : t -> t -> t
  CCInt.max : t -> t -> t

  CCInt.range_by : step:t -> t -> t -> t iter
  CCInt.range : t -> t -> t iter
  CCInt.range' : t -> t -> t iter
  CCInt.Infix : sig
                val ( -- ) : t -> t -> t iter
                val ( --^ ) : t -> t -> t iter
                val ( ** ) : t -> t -> t
              end ;;
```
Should be interesting to add/harmonize several functions.
e.g.
```ocaml
CCInt.to_float
CCInt.of_string_opt
CCInt32/Int64/Nativeint.pp
CCInt32/Int64/Nativeint.min
CCInt32/Int64/Nativeint.max ...
```

**Comment by hcarty** [comment]
> Map/Set/Hashtbl are opaque

Can we take advantage of the `*_seq` functions in `Stdlib` in 4.08+?  Older versions could use a partial hack by going through a list.

**Comment by c-cube** [comment]
They're typically included already, most containers modules do `include List` or something similar. the `*_std_seq` functions were a temporary solution, we could use the proper names now I suppose on >= 4.08

**Comment by hcarty** [comment]
Ah right, apologies I forgot about the `include`s
