### ISSUE TITLE
A Weak Set for Strings?

### ISSUE THREAD

**Issue by lindig** [c-cube/ocaml-containers#293]
This is just an idea for a module: applications that deal with a lot of strings and string comparisons could benefit from storing each string only once, which would also enable comparing strings by physical equality. The pool for these strings would be a weak set: strings would be GC’ed when they are only referenced from the set and no longer anywhere else. Does this make sense?

Increasing sharing between data structures is not limited to strings but I would expect that strings are a special case that is easier to support and use than the general case. There is a paper about hash consing in OCaml that also provides an implementation of a weak hash map. It’s probably worth studying. https://github.com/backtracking/ocaml-hashcons

**Comment by c-cube** [comment]
I believe you can just use the standard `Weak.Make` for that? I've been using heavily it for [hashconsing](https://github.com/c-cube/sidekick/blob/master/src/base-term/Hashcons.ml) and it works very well.

**Comment by lindig** [comment]
Thanks - I was not aware of Weak.Make - so we can close this.
