### ISSUE TITLE
Add hvbox around printed items to effect clean indentation w.r.t. start/stop strings

### ISSUE THREAD

**Issue by cemerick** [c-cube/ocaml-containers#295]
CCList prints list contents within the provided start/stop strings without a box:

https://github.com/c-cube/ocaml-containers/blob/d34b7588b028f3618cc44d3f4c6417295db586c8/src/core/CCList.ml#L1821-L1823

which means that the indentation of list items doesn't take the start string's length into account, e.g.

```
[[`Binding ((Name "box")), 
`Rule 18, 
`Rule 20], ...]
```

If a box were added around the contents of the list, like so:

```ocaml
      Format.pp_print_string fmt start;
      Format.pp_open_hvbox fmt 0;
      print fmt l;
      Format.pp_close_box fmt ();
      Format.pp_print_string fmt stop in
```

Much clearer output is generated, which is a big help with scanning larger nested structures:

```
[[`Binding ((Name "box")), 
  `Rule 18, 
  `Rule 20], ...]
```

The same thing would greatly improve the output of e.g. `Map.S.pp` and such as well.

**Comment by Gbury** [comment]
I think a more general solution would be for the start, sep and stop to be functions of type `Format.formatter -> unit -> unit`, that way, the user could simply specify very finely which box should be opened and how the start/stop/separator should interact with the box. For reference, i personally prefer to use `hvbox` usually, so forcing a `hovbox` would be a bit annoying.
Additionally, this new signature would be in line with the functions such as `Format.pp_print_list`.

**Comment by c-cube** [comment]
I think @Gbury got it. It should go into #290 . Otherwise you can use combinators from `CCFormat` such as `hvbox`, `hovbox`, `within`, or just use `fprintf` with a format string, which is what I tend to do.

**Comment by cemerick** [comment]
@Gbury Yeah, I was using a `hvbox` too.

I didn't think the `formatter -> unit -> unit` change was an option given #148. I guess if breakage is on the table, then this can go away.

Another option _could_ be to continue to accept strings, but treat them as format strings instead of literals. Then you could do `~start:"[@[" ~stop:"@]]"; technically breaking, I suppose, but I'd be surprised if code existed that would be problematic.

**Comment by c-cube** [comment]
It's on the table now that we're considering 3.0 !
