### ISSUE TITLE
dependency on CCMonomorphic?!

### ISSUE THREAD

**Issue by progman1** [c-cube/ocaml-containers#296]
how is it that CCMap has CCMonomorphic in its cmi/cmo import list?
ocamldep yields nothing and I cannot for the life of me see anything in the source
that gets to it indirectly. There is only a dependence on stdlib Map.
thanks

**Comment by c-cube** [comment]
Look in `src/core/dune`, there's a `-open CCMonomorphic` in there :-)

**Comment by progman1** [comment]
ah-ha! 
thank you!
