### ISSUE TITLE
Not sure I understand behaviour of List.pp

### ISSUE THREAD

**Issue by disteph** [c-cube/ocaml-containers#297]
I find it hard to understand the rationale of line-breaking on the following example. My output is:
```
$ ./main.native push pop
pop (5): SAT, ADV, ADJ, VER, NOUN
push (2): VER,
NOUN
```
from this code
```
let print_type word =
  ...
  let l = ... in
  let print fmt () =
    Format.fprintf fmt "%s (%i): %a\n" word (List.length l) (List.pp ~sep:", " pp_posType) l
  in
  Format.(output stdout print ())

let args = ref [];;
Arg.parse [] (fun a->args := a::!args) "";;
List.iter print_type !args
```
I understand the line break is performed by Format.pp_print_cut in List.pp, and is useful to avoid overful boxes, but I'm surprised there is no break for the first line with 5 items, which is longer, and there is one for the second. Am I missing something?

**Comment by c-cube** [comment]
I think you should never use `\n` in Format. try:

```ocaml
let print fmt () =
    Format.fprintf fmt "%s (%i): %a@." word (List.length l) (List.pp ~sep:", " pp_posType) l
  in
…
```

**Comment by disteph** [comment]
Thanks. It does this:
```
$ ./main.native push pop
pop (5): SAT, ADV, ADJ, VER,
NOUN
push (2): VER,
NOUN
```
Still not sure I understand; it's like the last `Format.pp_print_cut` has a different behaviour than the first ones. But no need to sweat about it, I can replace List.pp by an implementation specific to my use case that never introduce line breaks, which is what I want...
It was just in case it looked like a bug. If it's just my novice usage of formatting stuff...

**Comment by c-cube** [comment]
that's strange indeed. I typically put boxes a bit everywhere so I'd actually write `fprintf fmt "@[<2>%s (%d):@ @[%a@]@]@."` or something like that, to get some indentation :)

**Comment by disteph** [comment]
Well that worked. Thanks!
