### ISSUE TITLE
reduce function for cclist?

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#305]
does CCList need this function:
```ocaml
fun f -> function
| [] -> None
| h::t -> Some (CCList.fold_left f h t)
```
? i've seen this called 'reduce'. it's just a minor specialization of fold but is quite frequent in my personal experience.

**Comment by c-cube** [comment]
Why not, in which case I'd have `reduce` and `reduce_exn` I suppose. I'd rather reach for that when I already know the list is not empty.
