### ISSUE TITLE
CCFun Infix module

### ISSUE THREAD

**Issue by kwshi** [c-cube/ocaml-containers#312]
Various other modules, like `CCResult` and `CCList`, enclose their infix operators within an `Infix` sub-module, making it easier to expose/open access to just the operators without cluttering the namespace with all of the module's (non-infix) functions.  It seems like it would be convenient, and good for consistency's sake, to do the same with `CCFun`?

Such a change wouldn't have to be backwards-incompatible--the `Infix` module can still be `include`d at the module top-level (just as `CCList` and `CCResult` do right now), so that the infix operators can still be accessed from `open CCFun`, and existing code relying on this behavior doesn't break.

**Comment by c-cube** [comment]
I think it's doable, indeed. There are only two additional operators in there these days (`%` and `%>`), but it can be worth it.
