### ISSUE TITLE
Add chaining/sequencing combinator in CCFormat

### ISSUE THREAD

**Issue by kwshi** [c-cube/ocaml-containers#314]
# The problem

Currently, `CCFormat` lacks a clear combinator way to sequence two different printers.  

When printing things in boxes, the "combinators" approach provided by `CCFormat` is much nicer to use than the stdlib-compatible imperative `{open,close}_*box` API:
```ocaml
(* Format *)
pp_open_vbox fmt 2;
pp fmt a;
pp_close_box fmt ()

(* CCFormat combinators *)
vbox ~i:2
  pp
  fmt a
```

But suppose inside `...` I want to apply two printers `pp` and `pp'` in sequence.  Typically, I can imperatively sequence those two printers by writing
```
pp fmt a;
pp' fmt b
```
Clearly, this works with the imperative API (and is the usual way of chaining printers)--but in order for me to put the two printers within a box _combinator_ I have to define a new printer function:
```
vbox ~i:2
  (fun fmt () ->
    pp fmt a;
    pp' fmt b
  )
  fmt ()
```
which is not unbearable, but now quite a bit more noisy.  Another method to avoid imperative sequencing altogether is to use the `pair` combinator:
```
vbox ~i:2
  (pair ~sep:(return "") pp pp' (a, b))
  fmt ()
```
(and `triple`, `quad`, or even `list` for arbitrarily many sequence steps).  But this solution feels quite hacky and does not read that elegantly either.

# A solution from dbuenzli's [`Fmt`](https://github.com/dbuenzli/fmt)

`Fmt`'s attempt at a solution to this problem is an [`append`](https://erratique.ch/software/fmt/doc/Fmt/index.html#val-append) combinator for combining two printers.  It's defined as `append pp pp' fmt a = pp fmt a; pp' fmt a`.  It's not perfect, and it is a bit odd that both printers receive the same argument, which is not how you'd expect to do sequencing--but you can use `const` to pre-apply arguments and do something like
```
vbox ~i:2
  (append (const pp a) (const pp' b))
  fmt ()
```
While still a bit noisy (with the `const` calls), I find this much more readable, concise, and combinator-friendly.   And if you introduce infix operators `(@@@) = const` (similar to `@@` for usual function application, and for operator precedence rules) and `(<+>) = append` (`Fmt` chooses `++`, but I'm suggesting `<+>` here because it has lower operator precedence than `@`, per OCaml's [operator precedence rules](https://caml.inria.fr/pub/docs/manual-ocaml/expr.html#ss%3Aprecedence-and-associativity), and thus requires fewer parentheses):
```
vbox ~i:2
  (pp @@@ a <+> pp @@@ b)
  fmt ()
```
or maybe you're not a fan of `@@@`, in which we can just copy `Fmt`'s `++`:
```
vbox ~i:2
  (const pp a ++ const pp' b)
  fmt ()
```

# Conclusion

In any case, I personally find that having some combinator (and preferably with an infix version) for sequencing printers would be very nice; I'd like to see what you all think about this feature and its implementation details.

**Comment by c-cube** [comment]
I think it's a good idea. A few things are missing anyway:

- `append`
- `concat` (the list version of append? possibly with a `"@ "` in between each element, or a separator optional argument like `?(sep=return "@ ")`)
- `exn` to pretty-print exceptions
- `exn_backtrace` to print the exception and its backtrace if available

**Comment by kwshi** [comment]
Any thoughts on choice of operator?  Would it be better to
- follow `Fmt`'s choice of `++` for `append`, with nothing for `const`, or
- use `<+>` for `append` and `@@@` for `const`?

Also, another question worth raising is--should we add shorter aliases for existing functions (e.g., `Fmt` aliases `sp` to `pp_print_space`, `cut` to `pp_print_cut`, etc.)?  Things like `pp_print_space` are used so frequently that having a short alias like `sp` or even `space` would be noticeably more ergonomic (in fact even `return "@ "` is shorter than `pp_print_space`, rendering `pp_print_space` kind of pointless).  Plus, `CCFormat` already does this with things like `int` for `pp_print_int`, `string` for `pp_print_string`, etc.

**Comment by c-cube** [comment]
I think `<+>` is fine for binary append, and `const` is better than an infix operator.

`const pp a <+> const pp b` or `append_l [const pp a; return ";@ "; const pp b]` seem quite nice.

**Comment by c-cube** [comment]
Actually, would you mind opening a PR with `++` and maybe a few combinators for space/break?

**Comment by kwshi** [comment]
Sure, I'm on it.  Quick question, I remember there was something I needed to add, e.g. `@since`, to mark the version in which this appears--is it `latest`?  or `next`?  I don't recall; thanks.
