### ISSUE TITLE
CCPair doesn't have a Traverse submodule

### ISSUE THREAD

**Issue by brokenpylons** [c-cube/ocaml-containers#321]
A pair can be traversed as well, considering CCResult and CCList already have it would make sense to add it.

**Comment by c-cube** [comment]
it can only be traversed if both elements have the same type, right? It seems a bit overkill to me, I have a hard time imagining when I'd use that.

Or do you mean one traverse for each of both arguments?

**Comment by brokenpylons** [comment]
You are correct about the first part, but I meant just for the second argument like in the Haskell's [library](http://hackage.haskell.org/package/base-4.14.0.0/docs/Data-Traversable.html), but I guess one could be added for each of them.

**Comment by brokenpylons** [comment]
Anyways, so maybe something like this:

```ocaml
module type MONAD = sig
  type 'a t
  val map: ('a -> 'b) -> 'a t -> 'b t
  val return: 'a -> 'a t
  val (>>=): 'a t -> ('a -> 'b t) -> 'b t
end

module TraverseFst(M: MONAD): sig
  val map_m: ('a -> 'b M.t) -> ('a * 'c) -> ('b * 'c) M.t 
  val sequence_m: ('a M.t * 'b) -> ('a * 'b) M.t
  val fold_m: ('b -> 'a -> 'b M.t) -> 'b -> ('a * _) -> 'b M.t
end = struct
  let map_m f (x, y) = M.map (fun x -> (x, y)) (f x)
  let sequence_m p = map_m Fun.id p
  let fold_m f acc (x, _) = f acc x 
end

module TraverseSnd(M: MONAD): sig
  val map_m: ('a -> 'b M.t) -> ('c * 'a) -> ('c * 'b) M.t 
  val sequence_m: ('a * 'b M.t ) -> ('a * 'b) M.t
  val fold_m: ('b -> 'a -> 'b M.t) -> 'b -> (_ * 'a) -> 'b M.t
end = struct
  let map_m f (x, y) = M.map (fun y -> (x, y)) (f y)
  let sequence_m p = map_m Fun.id p
  let fold_m f acc (_, y) = f acc y 
end
```
In case you are still unsure about usefulness, I needed map_m for traversing a list of pairs, something along the lines of: ```TraverseList.map_m TraversePair.map_m f l```.

**Comment by kwshi** [comment]
What does the `needs_reporter_action` tag mean?

**Comment by c-cube** [comment]
> What does the `needs_reporter_action` tag mean?

that I'm not going to do anything :stuck_out_tongue_winking_eye:

**Comment by brokenpylons** [comment]
Its probably not that important. I don't really have time to create a proper pull request, so I closed it...
