### ISSUE TITLE
Incorrect docstrings for several Containers modules (CCList, CCString, CCArray)

### ISSUE THREAD

**Issue by Fourchaux** [c-cube/ocaml-containers#323]
See: https://github.com/OCamlPro/ocp-index/issues/143

**Comment by c-cube** [comment]
is it to be solved on ocp-index side, or ours? I'm not sure what causes this

**Comment by Fourchaux** [comment]
Waiting for a response from the pros of OCamlPro !!!

Actually, it seems almost all imported functions (with the include/open Foo) are displaying a wrong docstring.
Pb with ocp-index? 
What is a bit annoying is the different behavior of Containers_opam and Containers_dev.

BTW, you are using (in Containers_dev) _open CCShims__ and also _include CCShims__ (in CCArray). It's different, isn't it?

**Comment by c-cube** [comment]
well `include ` is for re-exporting, `open` just because it's convenient to have the more modern functions sometimes.

**Comment by Fourchaux** [comment]
The problem is not specific to Containers. Ouf...

I changed the title of OCamlPro/ocp-index#143

Wait and See.

**Comment by c-cube** [comment]
is this still an issue?

**Comment by Fourchaux** [comment]
Yes, still an issue.

@AltGr 's last comment:
https://github.com/OCamlPro/ocp-index/issues/143

This issue is not specific to Containers, you could possibly close it.
