### ISSUE TITLE
not longer 32-bit compatible

### ISSUE THREAD

**Issue by fdopen** [c-cube/ocaml-containers#327]
containers doesn't compile any longer on 32-bit systems: https://github.com/c-cube/ocaml-containers/blob/38d8fc2f9aa317d53d174a3db252111664b05f6b/src/core/CCInt.ml#L343-L345
```
# File "src/core/CCInt.ml", line 343, characters 30-48:
# 343 |   let b = b - ((b lsr 1) land 0x5555555555555555) in
# 
# Error: Integer literal exceeds the range of representable integers of type int
```

**Comment by c-cube** [comment]
Thank you, I will try to fix that shortly.

In the mean time, do you have any suggestion on how to get a local 32 bits toolchain on a 64 bits linux? And similarly, how to get 32 bits CI to avoid this kind of regressions?

**Comment by fdopen** [comment]
Locally: `opam switch create 4.10.0+32bit`
CI: Just also test Windows - it's a good idea anyway; e.g. with https://github.com/ocaml/ocaml-ci-scripts/blob/master/README-appveyor.md and a 32-bit switch like 4.10.0+mingw32c

**Comment by c-cube** [comment]
I could reproduce. I initially tried `4.08.1+32bit` but it didn't compile, whereas 4.10 is ok.

**Comment by c-cube** [comment]
can you give a try to the `wip-327` branch?

**Comment by fdopen** [comment]
the following command now succeeds under 32-bit switches:
```bash
opam pin add -n containers 'https://github.com/c-cube/ocaml-containers.git#wip-327'
opam install -t containers
```
