### ISSUE TITLE
CCSexp.parse_string crash/unexpected Invalid_argument exception

### ISSUE THREAD

**Issue by darrenldl** [c-cube/ocaml-containers#338]
As part of fuzzing [timere](https://github.com/daypack-dev/timere), cases which cause `CCSexp.parse_string` to raise `Invalid_argument("Char.chr")` exception are found.

## Manually minimised example

`\"\\N\"` where N is an integer > 255, e.g. `\"\\256\"`

A reprod is as follows:

```
let () =
  CCSexp.parse_string "\"\\256\" |> ignore
```

gives (with backtrace)

```
Fatal error: exception Invalid_argument("Char.chr")
Raised at file "stdlib.ml", line 30, characters 20-45
Called from file "src/core/CCSexp_lex.mll", line 46, characters 30-75
Called from file "src/core/CCSexp_lex.mll", line 77, characters 18-63
Called from file "src/core/CCSexp_lex.ml", line 169, characters 3-33
Called from file "src/core/CCSexp.ml", line 186, characters 30-35
Called from file "src/core/CCSexp.ml", line 229, characters 16-25
```

## Original cases from fuzzer

In case I missed something when minimising manually, following are some of the fuzzer discovered cases
- `\"\n\n<\\r9999999Y\\\"\n9\\99999999999999g9999999999999g999999g\"\n`
- `\"\n\r<\\t\023\n\203\\622222222\\\\\"\"\2032!2222\\\\\"\"`
- `\"\n\r<@t\023\n\203\\2222D2\n\r22222\01622222222222222222222222\203\\292242\222 2\\\\\">K2`
- `\"\n\r<\\t\023\n\203\\272222222\\\\\"\"\2032\0042222\\\\\"\"`
- `\"\023\n\203\\5222\n\r<\\t\023\n\203\\52222222\\\\\"2\\\216\216\216\216\216\\\\\"\216\216\216\216\216\216\216\216\216222222222222222\147`
- `\"\\722\02622222\\\\\n\r<\\\\\\\\\"\\222222222\\\\\"\"\2032!2222\\\\\"\"`

Crowbar/afl gives the same error for above inputs, e.g.

```
When given the input:

    "\"\n\n<\\r9999999Y\\\"\n9\\99999999999999g9999999999999g999999g\"\n"

the test threw an exception:

    Invalid_argument("Char.chr")
    Raised at file "stdlib.ml", line 30, characters 20-45
    Called from file "src/core/CCSexp_lex.mll", line 46, characters 30-75
    Called from file "src/core/CCSexp_lex.mll", line 77, characters 18-63
    Called from file "src/core/CCSexp_lex.ml", line 169, characters 3-33
    Called from file "src/core/CCSexp.ml", line 186, characters 30-35
    Called from file "src/core/CCSexp.ml", line 229, characters 16-25
```

**Comment by c-cube** [comment]
If you can run AFL again, that'd be super helpful! Or even contribute your instrumentation?

Now the module depends on `CCUtf8string` for these escapes , which could also use a **ton** of fuzzing.

**Comment by darrenldl** [comment]
Running it again now with master branch, seems to be clear.

I'm happy to contribute a PR to add a fuzzing suite in say `fuzz/` if that's what you meant? Not immediately obvious to me what to fuzz for CCUtf8string though, so I'll have to dig through the API and existing (q)tests a bit more.
