### ISSUE TITLE
0.7 failed compile in OPAM on OS X

### ISSUE THREAD

**Issue by mcclure** [c-cube/ocaml-containers#34]
I had containers 0.4.1 installed. It worked great. I did opam update. I did opam upgrade. containers was just plain gone. I did opam install containers. I got a long error.

	#=== ERROR while installing containers.0.7 ====================================#
	# opam-version 1.2.0
	# os           darwin
	# command      make build
	# path         /Users/mcc/.opam/4.02.1/build/containers.0.7
	# compiler     4.02.1
	# exit-code    2
	# env-file     /Users/mcc/.opam/4.02.1/build/containers.0.7/containers-96695-5f1023.env
	# stdout-file  /Users/mcc/.opam/4.02.1/build/containers.0.7/containers-96695-5f1023.out
	# stderr-file  /Users/mcc/.opam/4.02.1/build/containers.0.7/containers-96695-5f1023.err
	### stdout ###
	# ...[truncated]
	# /Users/mcc/.opam/4.02.1/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -no-alias-deps -w A -w -4 -w -44 -for-pack Containers_string -I src/string -o src/string/KMP.cmx src/string/KMP.ml
	# /Users/mcc/.opam/4.02.1/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -no-alias-deps -w A -w -4 -w -44 -for-pack Containers_string -I src/string -o src/string/levenshtein.cmx src/string/levenshtein.ml
	# touch src/string/containers_string.mli  ; if  /Users/mcc/.opam/4.02.1/bin/ocamlfind ocamlopt -pack -g -annot -bin-annot -I src/string src/string/KMP.cmx src/string/levenshtein.cmx -o src/string/containers_string.cmx  ; then  rm -f src/string/containers_string.mli  ; else  rm -f src/string/containers_string.mli  ; exit 1; fi
	# /Users/mcc/.opam/4.02.1/bin/ocamlfind ocamlopt -a src/string/containers_string.cmx -o src/string/containers_string.cmxa
	# + /Users/mcc/.opam/4.02.1/bin/ocamlfind ocamlopt -a src/string/containers_string.cmx -o src/string/containers_string.cmxa
	# /usr/bin/ranlib: object: src/string/containers_string.a(containers_string.o) malformed object (unknown load command 4)
	# ar: internal ranlib command failed
	# File "_none_", line 1:
	# Error: Error while creating the library src/string/containers_string.a
	# Command exited with code 2.
	### stderr ###
	# W: Cannot find source file matching module 'containers_misc' in library containers_misc
	# W: Cannot find source file matching module 'containers_string' in library containers_string
	# E: Failure("Command ''/Users/mcc/.opam/4.02.1/bin/ocamlbuild' src/core/containers.cma src/core/containers.cmxa src/core/containers.a src/core/containers.cmxs src/io/containers_io.cma src/io/containers_io.cmxa src/io/containers_io.a src/io/containers_io.cmxs src/sexp/containers_sexp.cma src/sexp/containers_sexp.cmxa src/sexp/containers_sexp.a src/sexp/containers_sexp.cmxs src/data/containers_data.c...[truncated]
	# make: *** [build] Error 1
	 
	 
	=-=- containers.0.7 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
	=> containers is now split into finer-grained sub-libraries, including
	       `containers.io`, `containers.iter`, `containers.sexp`, `containers.data`.
	       CCGen and CCSequence have been removed, consider using the libraries
	       `gen` and `sequence` on opam.
	Andis-Macbook:emily-ocaml mcc$ 

I mentioned this on #ocaml freenode and Whitequark mentioned:

     <whitequark> the problem is that os x is a [redacted]. their ar can't create empty archives, they know about it since, like, 2007, and they do not give a [redacted]
    [snip]
     <whitequark> mcc: http://caml.inria.fr/mantis/view.php?id=6550#c12345

 (Whitequark said a cuss!)

**Comment by mcclure** [comment]
Submitted before I meant to— a really important piece of information is that this was on Mac OS X 10.6 (yes, very old).

**Comment by mcclure** [comment]
Repeated test with opam install containers.0.6. Failed with same error.

[snip]
    # Error: Error while creating the library string/containers_string.a
    # Command exited with code 2.
    ### stderr ###
    # W: Cannot find source file matching module 'containers_misc' in library containers_misc
    # W: Cannot find source file matching module 'containers_advanced' in library containers_advanced
    # W: Cannot find source file matching module 'containers_string' in library containers_string
[snip]

**Comment by whitequark** [comment]
Waitwaitwait. Really sorry about this, but I latched onto the ar bug I knew, and missed the root cause of the issue, which is:

    /usr/bin/ranlib: object: src/string/containers_string.a(containers_string.o) malformed object (unknown load command 4)

Apparently this happens when you have a version mismatch (?) with regards to XCode command line tools: https://stackoverflow.com/questions/10390186/install-name-tool-reporting-malformed-object

Either way, this is not a bug in containers.

**Comment by mcclure** [comment]
Agreed, this is not a bug in containers.
