### ISSUE TITLE
Pretty printer prints unexpected new lines

### ISSUE THREAD

**Issue by macthecadillac** [c-cube/ocaml-containers#353]
When printing with the default options, the pretty printers of `CCList`, `CCPair` and `CCArray` always puts the last item on a new line. I haven't tested all the pretty printers in the library but those are what I've encountered and subsequently having to redefine the options every time I use it.

## Expected behavior
```
utop # Format.printf "%a\n" (List.pp Int.pp) [1; 2; 3; 4; 5];;
1, 2, 3, 4, 5
- : unit = ()
```

## Observed behavior
```
utop # Format.printf "%a\n" (List.pp Int.pp) [1; 2; 3; 4; 5];;
1, 2, 3, 4,
5
- : unit = ()
```

The same goes for the other two.

**Comment by macthecadillac** [comment]
This is not specific to `utop` either. It does the same thing for compiled programs.

Containers version: 3.2
OCaml version: 4.11.1

**Comment by c-cube** [comment]
it also does it with the standard library:

```ocaml
# Format.printf "%a@." Format.(pp_print_list CCFormat.int) [1;2;3];;
12
3
```

so I'm not sure the fault here lies with containers. With "@[<h>%a@]@." (horizontal box) it works:

```ocaml
# Format.printf "@[<h>%a@]@." CCFormat.(list int) [1;2;3];;1, 2, 3
- : unit = ()
```

**Comment by macthecadillac** [comment]
Ok thanks.
