### ISSUE TITLE
Flipped version of List.cons

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#354]
I needed `fun l e -> e :: l` a few times and did not find that in `List`. it's handy to have in particular in point-free `|>` style code. would that be a worthwhile addition? did i miss it?

**Comment by bluddy** [comment]
I believe it's usually called `snoc`.

**Comment by c-cube** [comment]
in my experience `snoc` can also mean adding an element at the end (e.g. for a finger tree or a functional deque). In the rest of containers it has this meaning.

**Comment by bluddy** [comment]
OK you're right. My bad.
