### ISSUE TITLE
CCPool: How to keep threads alive?

### ISSUE THREAD

**Issue by osener** [c-cube/ocaml-containers#360]
I would like to use CCPool & Futures to work with a C library that expects to be called from a single thread, and run in in a separate worker thread I send tasks to with Future. Making a pool with `max_size` results in very nice code that looks and works exactly how I want it, except CCPool terminates the thread after the task is done. 

I saw there used to be a `min_size` parameter that could've been what I'm looking for. I hacked around this by replacing `pool.cur_size > 0` condition [here](https://github.com/c-cube/ocaml-containers/blob/0a54024143ea08d665e6747da2aad0f2a0722a63/src/threads/CCPool.ml#L83) with `pool.cur_idle > 0`. This does what I want and always runs my futures in a specific thread, but I assume this is not right for most other uses of this module.

Is there an alternative way to do this with the current version of containers?  Thanks in advance!

**Comment by c-cube** [comment]
Hi! There is indeed nothing planned for that in the current version. I think the current condition is sub-optimal anyway, it could be `cur_idle > 0` (`cur_size > 0` should be an invariant since there's at least one running thread, the one checking this test) so we have at least one idle thread.

**Comment by osener** [comment]
Thank you for your quick response and the fix! https://github.com/c-cube/ocaml-containers/commit/cdf0e47cfb2445b1b5711e8a53b144e737430878 works great in my application.

**Comment by c-cube** [comment]
Heh, good, but it breaks the test suite so I need to work more on it :sweat_smile:

**Comment by c-cube** [comment]
would you mind testing it again? I refactored and I think I got the deadlocks out.

**Comment by osener** [comment]
`max_size = 1` with https://github.com/c-cube/ocaml-containers/commit/968cf5817fb3c87d110659e59d99d4ded43289c3 works great!

**Comment by c-cube** [comment]
should be fixed on master now!

**Comment by osener** [comment]
Thanks for going above and beyond to resolve this!
