### ISSUE TITLE
Add `CCSeq.exists` and `CCSeq.for_all`

### ISSUE THREAD

**Issue by bbc2** [c-cube/ocaml-containers#361]
Would you be interested in adding `exists` and `for_all` to `CCSeq` or are they considered outside of the scope of this package and better covered by `oseq`?

I'm asking because I find them useful and because `CCSeq` already has `exists2` and `for_all2`.

**Comment by c-cube** [comment]
That sounds reasonable indeed, I thought they were in the standard `Seq` but apparently not.
