### ISSUE TITLE
alias `Infix` with `Syntax` everywhere, deprecate `Infix`

### ISSUE THREAD

**Issue by c-cube** [c-cube/ocaml-containers#388]
seems like the trend is using `Syntax` (e.g in lwt), and it's more accurate than `Infix` for the new let operators.

**Comment by FardaleM** [comment]
In Lwt, the module Infix still exists and is for the infix operator like `>>=`. The module Syntax contains `let*` and other. Currently the monadic let bindings are in the module Infix, but we can have a separate module Syntax for them.

**Comment by c-cube** [comment]
good point.
