### ISSUE TITLE
make Hashtbl.Make richer 

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#419]
Would it be possible to include all of the convenience functions in Hashtbl also in the specialized hash tables generated by Hashtbl.Make? Right now one gets only a barebones module.

**Comment by c-cube** [comment]
isn't this https://github.com/c-cube/ocaml-containers/issues/46 ?

**Comment by nilsbecker** [comment]
ah i'm sorry i must have forgotten. so i tried it out again: after opening containers i can `Hashtbl.Make'(Int)` which gives me what i was asking for. for some reason i did not stumble upon `Make'` when i was looking for that recently.

Incidentally, in utop, `#require containers.top` complains that `CCHashtbl.pp has the wrong type for a printing function.`

**Comment by nilsbecker** [comment]
... and again i forgot that this already has an issue ;)
