### ISSUE TITLE
segfault using CCVector with iterator invalidation

### ISSUE THREAD

**Issue by gasche** [c-cube/ocaml-containers#423]
```ocaml
let vec = CCVector.of_list [1; 2; 3]
let () =
  CCVector.fold (fun () v ->
    print_int v;
    if v = 2 then begin
      CCVector.clear vec;
      CCVector.shrink_to_fit vec;
   end
  ) () vec
```

On my machine, this program prints a lot of numbers and quickly segfaults.
I think that the CCVector implementation should be *very* careful about its use of `Array.unsafe_{get,set}` functions.

**Comment by c-cube** [comment]
good catch, I see that all the multicore-related memory model issues have left their mark on you :). The solution is pretty simple, I think: capture `v.vec` and `v.size` before iterating.

**Comment by gasche** [comment]
Yes, this is also the solution that I had in mind. I'm impressed by your fixing speed :-)

(I'll post a comment to the PR.)

**Comment by c-cube** [comment]
you caught me at a good time :)
