### ISSUE TITLE
folding on a sequence as a sequence

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#435]
i saw this in igarnier/prbnmcn-dagger:

```
(** [fold_unfold f state seq] folds [f] over [seq] and constructs lazily
   a sequence out of each outcome. *)
let rec fold_unfold f state seq =
  match seq () with
  | Seq.Nil -> Seq.nil
  | Seq.Cons (elt, tail) ->
      let (state, elt) = f state elt in
      fun () -> Seq.Cons (elt, fold_unfold f state tail)
```
which i  could not find an equivalent of in CCSeq. Sounded like a logical addition to it, to me. i think it's the equivalent of
```
let fold_sequence f init seq =
  let d = Seq.to_dispenser seq in
  let fold_step x =
    d () |> Option.map (fun y ->
        let z = f x y in z, z) in
  Seq.unfold fold_step init
```
but the latter one is not really an improvement i think. not sure if there are undesired complications due the the presence of state.

**Comment by c-cube** [comment]
this should probably go into [oseq](https://github.com/c-cube/oseq/), shouldn't it?

**Comment by nilsbecker** [comment]
ah i wasn't aware of oseq. is this not actually the same as Oseq.fold_map?

**Comment by c-cube** [comment]
Looks like it, but note that the function in `OSeq.fold_map` returns
only the next state, not a pair of a state and element to yield. However
`unfold_scan` looks exactly like your definition.

**Comment by c-cube** [comment]
Indeed, it's separate so that containers isn't a contains-it-all (!) library. Note that `CCSeq` exists but is pretty basic.

**Comment by nilsbecker** [comment]
agreed. there is a balance to be found. 

my expectation was that if a module exists in containers, it's going to add the most important bits missing from Stdlib. possibly but not surely, the functions above belong to that class... maybe one could reconsider if they are asked for repeatedly.

**Comment by c-cube** [comment]
Indeed. In the mean time I think it's fine if they live only in OSeq :)
