### ISSUE TITLE
Bug with CCVector of Int32

### ISSUE THREAD

**Issue by RafaelBocquet** [c-cube/ocaml-containers#454]
The following code 
```ocaml
let () =
  let arr : Int32.t CCVector.vector = CCVector.create () in
  CCVector.push arr (Int32.of_int 123456);
  Format.printf "%d\n" (Int32.to_int (CCVector.get arr 0));
  let x = CCVector.get arr 0 in
  Format.printf "%d\n" (Int32.to_int x)
```
produces the following output:
```
123456
1024
```
when compiled to native code (`ocamlfind ocamlopt -linkpkg -package containers -o main main.ml`).

It produces the expected output when compiled to bytecode (`ocamlfind ocamlc -linkpkg -package containers -o main main.ml`).

**Comment by c-cube** [comment]
Sorry it took me so long to look at this. I _think_ it's a compiler issue, I got a small repro that only requires this from the `Vec` module:

```ocaml
type 'a t = { mutable vec: 'a array }

let push self x = self.vec <- [|x|]

let[@inline] get self i =
  if i >= Array.length self.vec then invalid_arg "ohno";
  Array.unsafe_get self.vec i
```

so I think inlining across module must lose some information. Please try the main branch to see if my fix works for you too!

**Comment by c-cube** [comment]
https://github.com/ocaml/ocaml/issues/13448 I opened an upstream bug report btw, thank you @RafaelBocquet :)
