### ISSUE TITLE
Hashtbl when opening containers

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#46]
this is a FIXME in containers.ml. what is the best way to use CCHashtbl for now?

**Comment by c-cube** [comment]
I didn't find how to expose an extension of `Hashtbl` as `Containers.Hashtbl`, because of sub-modules. However, you can still use `CCHashtbl` directly:

```ocaml
let tbl = CCHashtbl.of_list [1, "1"; 2, "2"] in
Hashtbl.find tbl 1
```

or:

```ocaml
module H = CCHashtbl.Make(CCInt)

let tbl = H.of_list [1, "1"; 2, "2"]
```

**Comment by nilsbecker** [comment]
ok, thanks. so when i use the specialized modules, (`H`  above) then these will include both the standard and `CCHashtbl` functions?

**Comment by c-cube** [comment]
Yes, the specialized module includes the signature `Hashtbl.S`. In practice I do use specialized tables a lot :)

**Comment by c-cube** [comment]
This should be solved, actually, there is a `Hashtbl` module in `Containers` since 0.14. But it's not 100% complete because of the sub-module clashes. If it's sufficient for you, can you close the issue?

**Comment by nilsbecker** [comment]
i don't understand fully what sub-module clashes means here. if there is remaining unexpected behavior for the user maybe a hint in the docs would help. otherwise i think this is fine.

**Comment by c-cube** [comment]
Actually, I might be able to fix it by breaking a bit compatibility (!!).
I will have to rename `CCHashtbl.S` into `CCHashtbl.Full` (for example).
