### ISSUE TITLE
file naming bug?

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#47]
i just tried to use CCInt and got this:

    Error: Wrong file naming: $HOME/.opam/4.02.3/lib/containers/cCint.cmi
    contains the compiled interface for 
    CCint when CCInt was expected
    Command exited with code 2.

**Comment by nilsbecker** [comment]
this was my own naming error. i was misled by the fact that a file inside of the distribution was apparently wrongly named

**Comment by c-cube** [comment]
Well, I'd like all the issues to get solved that quickly :-)
