### ISSUE TITLE
print function in Hashtbl.Make

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#48]
the print combinator function contains this line (164):

    Format.pp_print_string fmt "@[<hov2>tbl {@,";

which for me seems to result in literal output of the control characters. it should probably be `fprintf` or similar?

**Comment by c-cube** [comment]
indeed, the function is incorrect in `Make` but no for polymorphic tables. I'll fix it. Do you mind waiting for the next normal release (in one or two months at most) or do you really want a bugfix release?

**Comment by nilsbecker** [comment]
it's not so urgent for me, next release should be fine

**Comment by c-cube** [comment]
Ok, fine then, sholud be fixed by 92510d2
