### ISSUE TITLE
Char.print ?

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#49]
i stumbled upon the fact that there is no Char module and therefore also no Char.print (analogous to Int.print etc) might this be a worthwhile addition?

**Comment by c-cube** [comment]
Indeed, it should be useful. I should also add `CCFormat.char`, which is missing for no reason.

**Comment by nilsbecker** [comment]
great!

**Comment by c-cube** [comment]
See commit c71dfcf

**Comment by c-cube** [comment]
Is it fine for you?

**Comment by nilsbecker** [comment]
sure, it should work as a printer, right? perfect.

**Comment by c-cube** [comment]
yes, if you use `Format`. I did not add the `Buffer` version, but I should.
