### ISSUE TITLE
Containers.Hashtbl in 0.14 missing ('a,'b) t?

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#53]
it is in the source but i am getting compilation errors complaining about missing `Hashtbl.t` . also, in utop,`#typeof Hashtbl` (after opening `Containers`) does not show the type ?!

**Comment by c-cube** [comment]
Sorry, I used `:=` instead of `=`. I will make a bugfix release soon.

**Comment by c-cube** [comment]
bugfix release should be in, see https://github.com/ocaml/opam-repository/pull/5122
