### ISSUE TITLE
Missing infix operators for half-open ranges

### ISSUE THREAD

**Issue by eras** [c-cube/ocaml-containers#56]
The new CCList.Infix.(--) is nice, but it would be even nicer to have an alternative operator more suitable for dealing in algorithms with dynamic input, where half-open ranges are often seen. I suggest using --< which communicates nicely the fact that the right end of the range is open, ie. 1 --< 3 = [1; 2].

The empty range would be produced if the left and right bounds are the same. 1 --< 1 = [].

--< should also not automatically choose to make a descending range, but instead require that the second argument is never less than the first argument. The Invalid_argument in this situations seems appropriate to me, if Containers doesn't make use of something else.

If the user desires to write a descending range, he may choose to use the non-infix functions for that, or possibly List.rev. In practice I find descending ranges be much more rare than ascending ones, and in particular there are basically zero cases where the same piece of code would deal with ranges going either way, depending on arguments. So it's best to signal about those cases, as they are likely indicative of an error.

The --< operator should be provided in all the modules that currently provide --.

**Comment by c-cube** [comment]
It makes sense, indeed. The only thing I have to make my mind on is the decreasing range: there are some operators that exclude the right bound in containers, and it would make more sense to provide an infix alias to them than to reimplement a slightly different behavior, I think.

**Comment by c-cube** [comment]
I will add this soon, but probably named `(--^)` by compatibility with batteries.

**Comment by c-cube** [comment]
- [x] `CCArray`
- [x] `CCVector`
- [x] `CCList`
- [ ] `CCFQueue`
- [ ] `CCRAL`
- [ ] `CCKList`
