### ISSUE TITLE
containers v0.16 requires oasis

### ISSUE THREAD

**Issue by modlfo** [c-cube/ocaml-containers#59]
I installed containers from opam and it picked version 0.16. This version requires oasis to be installed. Oasis requires a lot of dependencies and it's hard to install in windows (MSVC port). My guess is that the static version of the build system (oasis setup) was no created before making the release.

**Comment by c-cube** [comment]
Indeed, this results from using opam-publish and not realizing the `opam` file in the repository is a dev version that requires oasis. I will make a bugfix release very soon (but be aware that currently the opam repository doesn't update).

**Comment by c-cube** [comment]
https://github.com/ocaml/opam-repository/pull/5908 should do the trick.

**Comment by c-cube** [comment]
It seems to be fixed. Please re-open if you still have issues.
