### ISSUE TITLE
Core style prefix/suffix functions

### ISSUE THREAD

**Issue by rgrinberg** [c-cube/ocaml-containers#66]
These are best explained through type signatures:

```
val chop_suffix : t -> suffix:t -> t option

val chop_prefix : t -> prefix:t -> t option
```

These are very useful and I often myself reaching them for them. Would be great if containers had them as well. Obviously the labels/names will need to be adjusted.

Apologies if containers already has them. I'm still learning the ropes.

**Comment by c-cube** [comment]
Right. Before I forget, there are also filter/filter_map on strings that should be added.

**Comment by c-cube** [comment]
done in f8bb365c94a94135a87a9525aba7a40cca28499e
