### ISSUE TITLE
Question: any reason why there is no CCArray.get_opt : 'a t -> int -> 'a option?

### ISSUE THREAD

**Issue by little-arhat** [c-cube/ocaml-containers#70]
subj.

**Comment by c-cube** [comment]
I never had the need for it (usually, since arrays have a fixed length, you can know before hand whether an index is valid or not). I can add it though.

**Comment by little-arhat** [comment]
Yes, it's true you can always check length, but I found myself always writing safe_get function, since it easier to compose optional types with CCOpt, than explicit if/else checks.

So, it seems to me, such function would be useful.
Thanks

**Comment by little-arhat** [comment]
Great, thanks!
