### ISSUE TITLE
containers.top produces warnings

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#71]
when requiring containers.top in utop i get warnings about wrong types of some printing functions...

**Comment by c-cube** [comment]
Ah, it's annoying indeed. I'll try to fix it, thanks!

**Comment by c-cube** [comment]
Ah, I understand why now. The printers that fail to install are printers on structural types; when the typechecker expands type aliases, it doesn't find the `'a printer -> 'a t printer` structure, so it complains.
I will simply remove these printers…
