### ISSUE TITLE
bind in CCOpt

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#72]
is there a reason that bind is only present in infix form in CCOpt? i'm asking since i just came across a situation where the normal bind with signature `(a -> b t) -> a t -> b t` would have been handy because of the argument order.

**Comment by c-cube** [comment]
No particular reason.

**Comment by c-cube** [comment]
actually, there is `CCOpt.flat_map`!

**Comment by nilsbecker** [comment]
oops! i guess i did not look hard enough...

**Comment by c-cube** [comment]
I think the type is sufficient, I tend to favor `flat_map` rather than `bind`. It would be nice to have sth like `ocamloscope` though…
