### ISSUE TITLE
CCError generic printer

### ISSUE THREAD

**Issue by copy** [c-cube/ocaml-containers#73]
`CCError.pp` and `CCError.print` only accept a printer argument for the `'good` type, not for `'bad`:

 ```ocaml
val pp : 'a printer -> ('a, string) t printer
val print : 'a formatter -> ('a, string) t formatter
```

 I'm using non-string types for errors, so a `pp` method that takes two printers (like `CCMap.S.pp`) would be useful.

**Comment by c-cube** [comment]
Indeed, that is most reasonable.

**Comment by copy** [comment]
Cheers
