### ISSUE TITLE
CCString.Split.left doesn't split correctly when separator is longer than 1

### ISSUE THREAD

**Issue by copy** [c-cube/ocaml-containers#75]
```ocaml
utop # CCString.Split.left ~by:"bb" "abbc";;
- : (string * string) option = Some ("a", "bc")
```

I believe this should yield `Some ("a", "c")`

**Comment by copy** [comment]
On a slightly related note, it seems that the inline tests of `CCString.cppo.ml` and other cppo files aren't being run.

**Comment by c-cube** [comment]
indeed, the tests in `.cppo` files are not run. Thanks for the report.
