### ISSUE TITLE
no capital letter in file names

### ISSUE THREAD

**Issue by bobzhang** [c-cube/ocaml-containers#77]
it does not work well with git/case insensitive file system

**Comment by c-cube** [comment]
Can you explain what are the issues? I've never used a case insensitive filesystem. My style is moving _towards_ capitalizing files so that filenames match modules names…

**Comment by bobzhang** [comment]
Both Mac and Windows are case insensitive OS..

**Comment by c-cube** [comment]
It seems to compile well on mac OS and windows (and some projects of mine that depend on containers do, too), so what's the issue?
