### ISSUE TITLE
CCChar.{of,to}_int

### ISSUE THREAD

**Issue by copy** [c-cube/ocaml-containers#95]
The following functions would be useful:

- `CCChar.of_int : int -> char option`
- `CCChar.of_int_exn : int -> char`
- `CCChar.to_int : char -> int`

**Comment by c-cube** [comment]
`to_int` is just `Char.code`. The others, why not…

**Comment by copy** [comment]
> to_int is just Char.code. The others, why not…

Indeed, and `CCChar.of_int_exn` is `Char.chr`. Just suggesting these for naming consistency.
