### ISSUE TITLE
feature request: inverse of List.combine

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#96]
i did not find this function which i think is pretty basic and useful. is it really missing? the name List.split is unfortunately taken for something else. List.separate maybe? List.unzip? but then List.zip would be the natural word instead of List.combine.

**Comment by c-cube** [comment]
Wait, `List.split` *is* the inverse of `List.combine`. What behavior do you want?

**Comment by nilsbecker** [comment]
List.split for me has type `int -> 'a list -> 'a list * 'a list`. i want `('a * 'b) list -> 'a list * 'b list`. just the inverse of what combine does.

**Comment by Gbury** [comment]
I think you're confusing `List`, the stdlib module, with `CCList`

**Comment by nilsbecker** [comment]
hmm. the type above is for CCList.split. and it should anyway supersede the stdlib, no?

**Comment by c-cube** [comment]
That's a known issue. In fact, `CCList.split` will be removed in 1.0 to address exactly that.

**Comment by nilsbecker** [comment]
oh, ok.

**Comment by c-cube** [comment]
I'll close this, 1.0 should basically fix your problem.
