### ISSUE TITLE
feature request: something like Partition in Mathematica

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#97]
i.e. `int -> 'a list -> 'a list list` where the inside lists are groups of successive elements in the original list. optional arguments could allow skipping and overlapping groups.

**Comment by c-cube** [comment]
Just to be sure, this would be the expected behavior?

```ocaml
foo 3 [1;2;3;4;5;6;7;8] = [[1;2;3]; [4;5;6]; [7;8]]
```

**Comment by nilsbecker** [comment]
yes. one could think of yet another optional argument to allow it to drop insufficiently-long trailing sublists.

**Comment by c-cube** [comment]
Ok, dully noted. Can you please specify the list of optional arguments you want, and their expected behavior (small test cases, given as equations `foo=bar`, would be awesome)?

**Comment by nilsbecker** [comment]
let's see. 

mma actually drops insufficiently long sublists by default. maybe that is reasonable if you want lists of a uniform length. however in mma, list double as arrays so maybe there it's more important to get uniform output. 

so i think the dropping should definitely be adjustable, but am not sure about best default.

mma behavior:
```
foo 3 [1;2;3;4] = [[1;2;3]]
foo 3 [1;2] = []
foo 2 ~offset:2 [1;2;3;4] = [[1;2];[3;4]]
foo 2 ~offset:1 [1;2;3] = [[1;2];[2;3]]
foo 2 ~offset:3 [1;2;3;4;5;6] = [[1;2];[4;5]]
foo 3 ~drop_short:false [1;2;3;4] = [[1;2;3];[4]]
```
`foo 2 ~offset:i [1;2]` raises an exception whenever i <= 0. this is a bit ugly. is there a better way?

mma also has some more complicated options where the list is padded cyclically or from another list at the end to allow for constant-length sublists.

so one could 
1. set drop_short to true by default (mma)
2. set it to false by default 
3. introduce instead an argument `~pad` which accepts ``[`Drop|`None|`Cyclic|`From of 'a list]`` where `` `None`` means keeping short sublists at the end, `` `Cyclic`` makes sublist the same length by cyclic padding from the original list and `` `From l`` effectively pads the list with cyclic copies of `l`. there should be a default for `~pad` which is either `` `None`` or `` `Drop``.

options 1. and 2. would not include the padding functionality and might be leaner/better?

finally it would be good to have a way to do it from the end. I.e. the last sublist would always align with the end of the list and potentially the first would be  dropped/padded. so an optional `~align_end` which defaults to false. one could of course reverse and then reverse the sublists.

**Comment by nilsbecker** [comment]
obviously argument names and all of this are up for debate.

**Comment by c-cube** [comment]
That's interesting,  thanks for the (future) test cases. I will look into it.

**Comment by bluddy** [comment]
I like this function (I've implemented a simple version of it myself several times), and I also like the offset argument.

The ~pad/~drop seems too complex and is indeed driven by the need for uniform length, which seems mostly unnecessary. If such behavior is needed, I think it's simpler to just let the user deal with the last sub-list by calling an optional user function ~f_last with the last elements of the original list. The user then gets to construct whatever sub-list he wants there (the default being the id function), including the option of returning the empty list if he wants to drop the sub-list altogether.

**Comment by c-cube** [comment]
Should be sufficient. The optional argument `last` can be used to keep the last group of elements if it comes short, and to implement padding if required.
