### ISSUE TITLE
Error compiling containers 1.0 on FreeBSD

### ISSUE THREAD

**Issue by orbitz** [c-cube/ocaml-containers#98]
/usr/home/orbitz/.opam/4.03.0+flambda/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -safe-string -short-paths -no-alias-deps -w A -w -4 -w -44 -I src/iter -o src/iter/CCKList.cmx src/iter/CCKList.ml
    + /usr/home/orbitz/.opam/4.03.0+flambda/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -safe-string -short-paths -no-alias-deps -w A -w -4 -w -44 -I src/iter -o src/iter/CCKList.cmx src/iter/CCKList.ml
    >> Fatal error: When simplifying [Project_var], the closure ID fair_app_partial_fun/3428 in the approximation of the set of closures did not match the closure ID map_partial_fun/3438 in the [Project_var] term.  Approximation: { descr=(closure:
    fair_app_partial_fun/3428 from { descr=(set_of_closures:
    fair_app_partial_fun/3428 invariant_params={ (param/3432 { }) } freshening={ vars_within_closure
    { }, closure_id { } }) var=set_of_closures/3433 symbol=<no symbol> }) var=a/3549 symbol=<no symbol> }
     Var-within-closure being projected: f/3440

    Fatal error: exception Misc.Fatal_error

**Comment by c-cube** [comment]
This looks like a compiler error to me (flambda?). Could you please try with 4.03 without flambda?

**Comment by orbitz** [comment]
Looks like it's related to flambda on 4.03.0.  It seems to compile fine on 4.04.0 and 4.04.0+flambda.

Not sure if you want to support 4.03.0+flambda, if not, feel free to close!

**Comment by c-cube** [comment]
if it works on 4.04+flambda I think the compiler bug has been fixed, so I can close this.
